### PR TITLE
Rebase to ingest fix for Route CR defaulting disparities.

### PR DESCRIPTION
**Pull request by benluddy**
To be replaced by an OCP rebase once admission changes have merged.

When serialized in the request as the empty string, spec.to.kind is defaulted to "Service".

```
$ cat <<EOF | oc apply -f-
> apiVersion: route.openshift.io/v1
> kind: Route
> metadata:
>   name: hello-microshift
> spec:
>   to:
>     kind: ""
>     name: hello-microshift
> EOF
route.route.openshift.io/hello-microshift created
$ oc get route hello-microshift -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-12-13T16:47:57Z"
  generation: 1
  name: hello-microshift
  namespace: default
  resourceVersion: "333208"
  uid: 2b77318d-806e-4ac4-b93d-d2e352129595
spec:
  host: hello-microshift-default.apps.microshift.example.com
  to:
    kind: Service
    name: hello-microshift
    weight: 100
  wildcardPolicy: None
```

When spec.tls is serialized in the request as an empty object, spec.tls.termination defaults to "edge":

```
$ cat <<EOF | oc apply -f-
> apiVersion: route.openshift.io/v1
> kind: Route
> metadata:
>   name: hello-microshift
> spec:
>   to:
>     name: hello-microshift
>   tls: {}
> EOF
route.route.openshift.io/hello-microshift created
$ oc get route hello-microshift -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-12-13T16:49:32Z"
  generation: 1
  name: hello-microshift
  namespace: default
  resourceVersion: "333263"
  uid: c2ded194-1c5a-43b2-840c-6b245f07655f
spec:
  host: hello-microshift-default.apps.microshift.example.com
  tls:
    termination: edge
  to:
    kind: Service
    name: hello-microshift
    weight: 100
  wildcardPolicy: None
```

Uppercase value "Edge" for spec.tls.termination is converted to "edge":

```
$ cat <<EOF | oc apply -f-
> apiVersion: route.openshift.io/v1
> kind: Route
> metadata:
>   name: hello-microshift
> spec:
>   to:
>     name: hello-microshift
>   tls:
>     termination: Edge
> EOF
route.route.openshift.io/hello-microshift created
$ oc get route hello-microshift -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-12-13T16:51:16Z"
  generation: 1
  name: hello-microshift
  namespace: default
  resourceVersion: "333295"
  uid: 0cf79a40-3ad4-47a6-9acd-68ba0095cf22
spec:
  host: hello-microshift-default.apps.microshift.example.com
  tls:
    termination: edge
  to:
    kind: Service
    name: hello-microshift
    weight: 100
  wildcardPolicy: None
```

When serialized in the request as "", spec.wildcardPolicy defaults to "None":

```
$ cat <<EOF | oc apply -f-
> apiVersion: route.openshift.io/v1
> kind: Route
> metadata:
>   name: hello-microshift
> spec:
>   to:
>     name: hello-microshift
>   wildcardPolicy: ""
> EOF
route.route.openshift.io/hello-microshift created
$ oc get route hello-microshift -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-12-13T16:53:50Z"
  generation: 1
  name: hello-microshift
  namespace: default
  resourceVersion: "333344"
  uid: 22e55670-691e-4f6c-9c7b-64534a1a2044
spec:
  host: hello-microshift-default.apps.microshift.example.com
  to:
    kind: Service
    name: hello-microshift
    weight: 100
  wildcardPolicy: None
```

### CODE REVIEW

**Comment by benluddy** [comment]
> bot things

This looks like a misconfiguration given that microshift's main branch is still tracking release-4.12, right?

/retitle Rebase to ingest fix for Route CR defaulting disparities.

**Comment by pmtk** [comment]
We merged a [rebase PR](https://github.com/openshift/microshift/pull/1198) with (almost; I think this does not include arm images) the same content - I think this can be closed, can you confirm @benluddy?

**Comment by benluddy** [comment]
/hold

That should do it, but I'll recompile and test to be entirely sure.

**Comment by benluddy** [comment]
Yes, checked the same smoke tests using a nightly from today and they worked fine. Thanks!

/close

**Pull request closed without merging**
