### PR TITLE
NP-648: single pod ovnk

### PR DESCRIPTION
**Pull request by zshi-redhat**

### CODE REVIEW

**Comment by ggiguash** [comment]
This is a 4.13 release functionality. Holding the PR until the 4.12 branch is created.
/hold

**Comment by mangelajo** [comment]
@ggiguash @zshi-redhat I have observed a stable drop of 50MBi of RAM when setting it up together in one pod tested on my system.

@zshi-redhat Not sure if it's feasible, but... using a single container, in addition, could bring around an extra 20MBi drop. (all the associated conmon and bash processes...) I don't know if it's worth though.

**Comment by dhellmann** [comment]
/retest

We don't have to do it this time, but this seems like an example of where we might need upgrade logic to clean up old settings (the ClusterRole, for example). Something to keep in mind for when we get to the point where upgrades are fully supported.

**Comment by zshi-redhat** [comment]
> /retest
> 
> We don't have to do it this time, but this seems like an example of where we might need upgrade logic to clean up old settings (the ClusterRole, for example). Something to keep in mind for when we get to the point where upgrades are fully supported.

added this comment to the ovnk upgrade ticket.

**Comment by zshi-redhat** [comment]
> @ggiguash @zshi-redhat I have observed a stable drop of 50MBi of RAM when setting it up together in one pod tested on my system.
> 
> @zshi-redhat Not sure if it's feasible, but... using a single container, in addition, could bring around an extra 20MBi drop. (all the associated conmon and bash processes...) I don't know if it's worth though.

@mangelajo how did you measure the memory?

**Comment by zshi-redhat** [comment]
/unhold

remove the hold flag added by openshift bot due to 3 failed retest.

**Pull request merged**
