### PR TITLE
USHIFT-1638: rebase with kube 1.28 update

### PR DESCRIPTION
**Pull request by dhellmann**
This PR includes the automatically generated rebase from #2444 and some
corrective patches to fix an import that has moved and to apply a carry
patch to k8s to restore a missing constructor.

amd64: 4.15.0-0.nightly-2023-10-05-021229
arm64: 4.15.0-0.nightly-arm64-2023-10-05-220031
prow job: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-microshift-main-rebase-on-nightlies/1710157984186765312

- cluster-csi-snapshot-controller-operator embedded-component 9a67364ca9b2761f9bfffd7f600018788f94a5dd to 809d4caef5ba829e1951985128f5bef29c2be560
  - e9ecc1e 2023-09-16T17:48:03+00:00 Updating ose-cluster-csi-snapshot-controller-operator images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/da6a5af1fa96762cc8410f09fc28c0457280f59a/images/ose-cluster-csi-snapshot-controller-operator.yml
  - 1c9d074 2023-09-05T16:16:43-04:00 Move readonlyRootFilesystem to the right place
  - 8a0f49a 2023-08-20T17:46:02-07:00 [STOR-1443](https://issues.redhat.com//browse/STOR-1443): Restart webhook Pods if `csi-snapshot-webhook-secret` changed
  - 50bde7e 2023-08-20T17:42:56-07:00 [STOR-1443](https://issues.redhat.com//browse/STOR-1443): Add list+watch RBAC for "secrets" in Hypershift and standalone RBAC yamls

- cluster-dns-operator embedded-component f5f12b76e1d19ca9c98013158a0a5aae278a4d57 to c03919da0952618d02225d3e58cb391806c9e2f0
  - b15beb2 2023-09-21T02:18:02-04:00 TestCoreDNSDaemonSetReconciliation: Fix nil in log
  - d055e4e 2023-09-21T02:07:49-04:00 test/e2e: Set controller-runtime logger
  - bdef901 2023-09-16T09:15:32+00:00 Updating ose-cluster-dns-operator images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/da6a5af1fa96762cc8410f09fc28c0457280f59a/images/ose-cluster-dns-operator.yml

- cluster-ingress-operator embedded-component cd9777112490675bcb38d1aaff13e6082965eeb5 to a10d93e71e59779eed2f5e904a5a15ef4680fb41
  - 7ee37ab 2023-09-25T13:12:30-04:00 OCPBUGS-1689: Add unit test for the route-metrics controller reconcile function.
  - 1311288 2023-09-25T12:35:13-04:00 OCPBUGS-3541: Don't create route_metrics_controiller_routes_per_shard metrics for ingress controllers that are not admitted
  - 556ddd8 2023-09-17T21:29:45+00:00 Updating ose-cluster-ingress-operator images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/da6a5af1fa96762cc8410f09fc28c0457280f59a/images/ose-cluster-ingress-operator.yml
  - 806de29 2023-09-13T13:15:48-04:00 OCPBUGS-18248: Prevent GatewayClass from getting recreated
  - 4aa579b 2023-09-05T14:24:15-04:00 Add test for captured cookie truncation
  - fa716b8 2023-09-05T13:57:30-04:00 TestMTLSWithCRLs: only try to parse HTTP status code from curl output when stdout is long enough.
  - f021ba0 2023-08-28T14:01:56-04:00 Move getPods to test/e2e/util_test.go

- cluster-kube-apiserver-operator embedded-component cbe6c19dd6d139ac3aad15220b8cbcb791fbe79a to c1fb42cb128d60386aabde57bb62cc7fc626a980
  - 4f92e41b 2023-09-28T14:04:27-04:00 Update required GV for ValidatingAdmissionPolicy gate.
  - 0942d77a 2023-09-28T10:03:47-04:00 Update "deprecated API in use" alert expressions for 1.28.
  - a4b9aa71 2023-09-27T13:39:37+02:00 bump(openshift/client-go,library-go)
  - e5d67309 2023-09-25T08:52:12+03:00 installerpod: change pod manifest mode to 0600
  - b1837ef8 2023-09-15T14:13:46-04:00 remove featuregate upgradeable controller that moved to cluster-config-operator
  - 7ce913ad 2023-09-15T13:04:01-03:00 bump(k8s): go mod vendor
  - 43375967 2023-09-15T13:03:49-03:00 bump(k8s): bump openshift/{api,client-go,library-go}
  - 779c2dbb 2023-09-14T16:50:13-03:00 bump(k8s): go mod vendor
  - 61e5982e 2023-09-14T16:50:13-03:00 bump(k8s): update k8s.io/* dependencies to v1.28.2
  - 497c1aa5 2023-09-11T11:10:28-03:00 bump(k8s): go mod vendor
  - cb3354eb 2023-09-11T11:10:15-03:00 bump(k8s): update k8s.io/* dependencies to v1.28.1
  - a57919a9 2023-09-05T19:46:02+02:00 manifests: don't include recording rules when console is disabled
  - 3faf3f33 2023-09-05T17:27:55+02:00 manifest: remove kube-apiserver PrometheusRule

- cluster-kube-controller-manager-operator embedded-component d95b0c25ba55c4ef8e09e56461562ee60b22d51c to ee4020fad5112dbb054dc5988bf0be97edf9d803
  - 697e9dd 2023-09-27T13:40:36+02:00 bump(openshift/client-go,library-go)
  - 333eaf6 2023-09-25T08:56:58+03:00 installerpod: change pod manifest mode to 0600
  - 44d7739 2023-09-17T20:04:36+00:00 Updating ose-cluster-kube-controller-manager-operator images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/da6a5af1fa96762cc8410f09fc28c0457280f59a/images/ose-cluster-kube-controller-manager-operator.yml
  - 234a70d 2023-09-15T13:07:34-03:00 bump(k8s): go mod vendor
  - 58529e0 2023-09-15T13:07:16-03:00 bump(k8s): bump openshift/{api,client-go,library-go}
  - 9c3916c 2023-09-14T16:52:31-03:00 bump(k8s): go mod vendor
  - c401181 2023-09-14T16:52:15-03:00 bump(k8s): update k8s.io/* dependencies to v1.28.2
  - bf34782 2023-09-11T11:22:14-03:00 bump(k8s): go mod vendor
  - c7a16e2 2023-09-11T11:22:03-03:00 bump(k8s): update k8s.io/* dependencies to v1.28.1

- cluster-kube-scheduler-operator embedded-component db92b6d9fcf410aa24efc4a70c4114925bb7b797 to b8245a4b3da2d8d22ab81466c2a949e52909ecf4
  - 279b345 2023-09-27T13:41:32+02:00 bump(openshift/client-go,library-go)
  - 9b40cab 2023-09-25T09:02:52+03:00 installerpod: change pod manifest mode to 0600
  - 3b3ff10 2023-09-16T21:0

The change list was truncated. See scripts/auto-rebase/changelog.txt in the PR for the full details.

/label tide/merge-method-squash

### CODE REVIEW

**Comment by pacevedom** [comment]
Added https://issues.redhat.com/browse/USHIFT-1748 to remove the patches once they are in openshift/kubernetes.

**Comment by dhellmann** [comment]
The composer API seems to have died:

```
sudo composer-cli sources add /home/ec2-user/microshift/_output/test-images/package-sources/microshift-crel.toml
ERROR: Add source TOML: Post "http://localhost/api/v1/projects/source/new": EOF
```

/test microshift-metal-tests

**Comment by dhellmann** [comment]
The composer API reported an error:

```
ERROR: Add source TOML: Post "http://localhost/api/v1/projects/source/new": EOF
```

/test microshift-metal-tests

**Comment by pacevedom** [comment]
Investigating the same failure locally, as it happened in a manually deployed cluster.

**Comment by pacevedom** [comment]
Retest when https://github.com/openshift/release/pull/44228 is merged.

**Pull request merged**
