### PR TITLE
USHIFT-1821: allow scenario steps to report being skipped

### PR DESCRIPTION
**Pull request by dhellmann**
/assign @ggiguash @pacevedom

### CODE REVIEW

**Comment by dhellmann** [comment]
It looks like the CI cluster lost the pod with the job in it. Trying again.

/test metal-periodic-test

**Comment by ggiguash** [comment]
The reason for failing the periodic test is not related to this PR and it will be fixed elsewhere.
/unhold 
/override ci/prow/metal-periodic-test

**Comment by dhellmann** [comment]
Image creation failed

/retest

**Pull request merged**
