### PR TITLE
USHIFT-333: update validation for tls in route crd

### PR DESCRIPTION
**Pull request by dhellmann**
Update to copy of file from
openshift/api@0b39f81154fa42abe26933181141ed4b4e3ad247

Note to reviewers: There were a lot of whitespace changes in the YAML file being updated, so I split this PR into 2 commits. The first updates the "base" by using a recent commit in openshift/api that was older than the validation change we care about. The second includes only that validation update.

### CODE REVIEW

**Comment by dhellmann** [comment]
I need to make sure we have the right process in place to keep this file up to date.

/hold

**Comment by dhellmann** [comment]
We're updating by hand for now, and have USHIFT-363 to remember to incorporate this file into the rebase automation when we are pulling content from HEAD again.

/hold cancel

**Comment by benluddy** [comment]
/lgtm

Confirmed that Routes generated by the ingress-to-route controller are passing validation with this schema update.

**Review by mangelajo — COMMENTED** [review]
/lgtm

**Pull request merged**
