### PR TITLE
USHIFT-1259: update configure-vm.sh to lock RHEL minor release

### PR DESCRIPTION
**Pull request by dhellmann**
When setting up a system with a subscription, lock it to the current
minor release. This prevents the system from being upgraded beyond
that minor release so we can be sure that we are testing on the
version we install. Add a flag to disable this behavior for systems
where we want to test upgrading past the installed version.

### CODE REVIEW

**Comment by dhellmann** [comment]
The relevant section of the [conformance job logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_microshift/1797/pull-ci-openshift-microshift-main-e2e-openshift-conformance-reduced/1657507854023659520/artifacts/e2e-openshift-conformance-reduced/openshift-microshift-infra-rpm-install-aws/build-log.txt)

```
+ source /etc/os-release
++ NAME='Red Hat Enterprise Linux'
++ VERSION='9.2 (Plow)'
++ ID=rhel
++ ID_LIKE=fedora
++ VERSION_ID=9.2
++ PLATFORM_ID=platform:el9
++ PRETTY_NAME='Red Hat Enterprise Linux 9.2 (Plow)'
++ ANSI_COLOR='0;31'
++ LOGO=fedora-logo-icon
++ CPE_NAME=cpe:/o:redhat:enterprise_linux:9::baseos
++ HOME_URL=https://www.redhat.com/
++ DOCUMENTATION_URL=https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9
++ BUG_REPORT_URL=https://bugzilla.redhat.com/
++ REDHAT_BUGZILLA_PRODUCT='Red Hat Enterprise Linux 9'
++ REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
++ REDHAT_SUPPORT_PRODUCT='Red Hat Enterprise Linux'
++ REDHAT_SUPPORT_PRODUCT_VERSION=9.2
+ sudo subscription-manager release --set 9.2
Release set to: 9.2
+ sudo subscription-manager release --show
Release: 9.2
+ sudo dnf clean all -y
Updating Subscription Management repositories.
Waiting for process with pid 14456 to finish.
Waiting for process with pid 14456 to finish.
Waiting for process with pid 14456 to finish.
27 files removed
```

**Comment by ggiguash** [comment]
@dhellmann, should we backport this issue to release-4.13?

**Pull request merged**
