### PR TITLE
[release-4.15] USHIFT-2208: add periodic test scenario for the standard tests on rpm-based system

### PR DESCRIPTION
**Pull request by dhellmann**
Manual backport of #2850

### CODE REVIEW

**Comment by dhellmann** [comment]
Updated to include part of https://github.com/openshift/microshift/pull/2746 from @eggfoobar

**Comment by dhellmann** [comment]
We will need to backport #2918 before we can merge this change.

**Comment by dhellmann** [comment]
The ARM job failed with an unrelated issue in the storage snapshot test. https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_microshift/2914/pull-ci-openshift-microshift-release-4.15-microshift-metal-tests-arm/1750172324713205760/artifacts/microshift-metal-tests-arm/openshift-microshift-e2e-metal-tests/artifacts/scenario-info/el92-src@storage/log.html

**Review by pacevedom — COMMENTED** [review]
/label cherry-pick-approved
/hold
Just in case QE wants to test it out as there were changes in selinux. Feel free to remove it.

**Comment by agullon** [comment]
hi @pacevedom I'd like to get this PR merged. Also created another PR to merge this changes into `release-4-14` branch: https://github.com/openshift/microshift/pull/3039

**Comment by dhellmann** [comment]
/label staff-eng-approved

@agullon I've added the missing label. I'll leave it up to you and @pacevedom to remove it when you're comfortable landing a CI change.

**Pull request merged**
