### PR TITLE
[release-4.14] USHIFT-2164: scenario and suite for testing rpm-based installation and upgrades

### PR DESCRIPTION
**Pull request by dhellmann**
This is a manual backport of #2861 

There was a conflict in cherry-picking eb402543395dd4a50bbefa724305e09074dbd385 that was resolved by removing the `TEST_EXECUTION_TIMEOUT` variable.

### CODE REVIEW

**Comment by dhellmann** [comment]
The new scenario is failing with `No keyword with name 'Command Should Work' found.` but works for me locally. I'm exploring why there is a difference.

**Comment by copejon** [comment]
In the rpm-test, something is breaking the Y-stream variable expansion:
[`['Error: \'rhocp-4.-for-rhel-9-x86_64-rpms\'`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_microshift/2865/pull-ci-openshift-microshift-release-4.14-microshift-metal-tests/1745159514115543040/artifacts/microshift-metal-tests/openshift-microshift-e2e-metal-tests/artifacts/scenario-info/el92-src@rpm-install/log.html#s1-k1-k7-k2-k1)

**Comment by dhellmann** [comment]
> In the rpm-test, something is breaking the Y-stream variable expansion: [`['Error: \'rhocp-4.-for-rhel-9-x86_64-rpms\'`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_microshift/2865/pull-ci-openshift-microshift-release-4.14-microshift-metal-tests/1745159514115543040/artifacts/microshift-metal-tests/openshift-microshift-e2e-metal-tests/artifacts/scenario-info/el92-src@rpm-install/log.html#s1-k1-k7-k2-k1)

Thanks, yeah, the script that dynamically figures out the version of the dependency repo to use is not in this branch. I added a commit to hard-code that value, since there's a 4.14 repo with good content in it.

**Comment by dhellmann** [comment]
The cause of failure isn't clear from the logs.

/test metal-periodic-test

**Pull request merged**
