### PR TITLE
USHIFT-5083: Always use qualified commit references in bootc kickstart

### PR DESCRIPTION
**Pull request by ggiguash**
Only review [this commit](https://github.com/openshift/microshift/pull/4249/commits/7dfaed2846b85c570a61ff5f2c54cbe9f76dff85). The others are fixing a build problem that's not been merged yet.

### CODE REVIEW

**Comment by ggiguash** [comment]
/test e2e-aws-tests-periodic
```
Tagging '192.168.122.1:5000/rhel9/rhel-bootc' as 'latest'
Tagging '192.168.122.1:5000/ubi9' as 'latest'
time="2024-11-29T09:41:20Z" level=fatal msg="copying image 4/4 from manifest list: reading blob sha256:f8b035150618a83f6e138b0843d47a77e1cb4d5fac81d3212df4533a74028272: fetching blob: received unexpected HTTP status: 500 Internal Server Error"
Tagging '192.168.122.1:5000/centos-bootc/centos-bootc' as 'latest'
time="2024-11-29T09:41:20Z" level=fatal msg="initializing source docker://192.168.122.1:5000/centos-bootc/centos-bootc:stream9: reading manifest stream9 in 192.168.122.1:5000/centos-bootc/centos-bootc: manifest unknown"
```

**Comment by pmtk** [comment]
/lgtm
/hold

Unhold in right time :)

**Pull request merged**
