### PR TITLE
PERFSCALE-2108: Enable logging for Microshift built-in kubelet metrics

### PR DESCRIPTION
**Pull request by sjug**
- Make external cadvisor process conditional
- Create role to create metrics service account
- Add firewall port for kubelet endpoint
- Create role to modify prometheus config
- Fix file location in microshift-start
- Append kubelet endpoint to prometheus config in playbook

### CODE REVIEW

**Review by dhellmann — COMMENTED** [review]
I take it from the setup that Prometheus is running outside of MicroShift?

/approve

**Comment by sjug** [comment]
> I take it from the setup that Prometheus is running outside of MicroShift?

The ansible logging tasks will set up Prometheus & Grafana on a specified host. I generally run the logging setup on a second host so I don't add resource consumption to the MicroShift node.

**Pull request merged**
