### PR TITLE
USHIFT-375: fix capitalization in show-config output

### PR DESCRIPTION
**Pull request by dhellmann**
/assign @fzdarsky
/type bug

### CODE REVIEW

**Comment by zshi-redhat** [comment]
LGTM

**Comment by fzdarsky** [comment]
/hold

Needs a few further changes so loading of configs also work correctly.

**Comment by fzdarsky** [comment]
Looks like the unit tests for configuration are broken. I've opened USHIFT-383 and create a PR. Once that's fixed, this PR should merge automatically.

**Comment by dhellmann** [comment]
> Looks like the unit tests for configuration are broken. I've opened [USHIFT-383](https://issues.redhat.com//browse/USHIFT-383) and will create a PR. Once that's fixed, this PR should merge automatically.

I can't reproduce that failure locally.

**Pull request merged**
