### PR TITLE
cluster-policy-controller

### LINKED ISSUE #303: [Enhancement]: Add cluster-policy-controller
#### What would you like to be added:
Add the [cluster-policy-controller](https://github.com/openshift/cluster-policy-controller) as an additional embedded service into the MicroShift binary.

#### Why is this needed:
The `cluster-policy-clontroller` allocates UIDs and SELinux labels for namespaces, allowing for example services like the service-ca as non-root user with randomised UID. It also manages cluster quota usage. Without it, manifests would need to be changed between OpenShift and Microshift, while the goal is to allow for workload portability.

### PR DESCRIPTION
**Pull request by sallyom**
Embedding the cluster-policy-controller requires too much reworking of code, I'm in favor of running cluster-policy-controller as a deployment. This way microshift won't be dependent on changes in openshift/library-go controllercmd code.

Added OpenShift Assets:
[namespace-security-allocation-controller-clusterrole](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/release-4.8/bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrole.yaml)
[namespace-security-allocation-controller-clusterrolebinding](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/release-4.8/bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrolebinding.yaml)
[kube-controller-manager static pod cluster-policy-controller container](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/release-4.8/bindata/v4.1.0/kube-controller-manager/pod.yaml)
[RangeAllocations CRD](https://github.com/openshift/api/blob/release-4.8/securityinternal/v1/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml)
[kube-controller-manager ns](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/release-4.8/bindata/v4.1.0/kube-controller-manager/ns.yaml)

Closes #303

### CODE REVIEW

**Comment by sallyom** [comment]
**Note:**  change in RunClusterPolicyController from 4.8, 4.9 - if we embed, will have to rework when bump to 4.9

release 4.9 cluster-policy-controller Run command: https://github.com/openshift/cluster-policy-controller/blob/release-4.9/pkg/cmd/cluster-policy-controller/policy_controller.go#L18 

release 4.8 cluster-policy-controller Run command: https://github.com/openshift/cluster-policy-controller/blob/release-4.8/pkg/cmd/cluster-policy-controller/policy_controller.go#L32

**Comment by sallyom** [comment]
@fzdarsky it works! I've added a commit to run service-ca deployment w/ NonRoot 1001:1001, same as ocp manifest
```
      securityContext:
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
```

**Comment by mangelajo** [comment]
@fzdarsky @sallyom did we decide how we want to go about this?, If we want to go this route we need to build multi-arch images for the cluster-policy-controller, I can handle that, just let me know.

thanks for looking at this sally!

**Comment by sallyom** [comment]
closing, we won't need this & if that changes can reopen

**Pull request closed without merging**
