### PR TITLE
OCPBUGS-6908: 4.12 Avoid firewalld flush of iptables

### PR DESCRIPTION
**Pull request by mangelajo**
cherry pick from https://github.com/openshift/microshift/pull/1300 (automatic cherry
pick failed with conflict on the microshift.spec file changelog entries)

    Avoid firewalld flush of iptables

https://issues.redhat.com/browse/NP-641
https://issues.redhat.com/browse/USHIFT-789
https://issues.redhat.com/browse/OCPBUGS-6860

### CODE REVIEW

**Comment by dhellmann** [comment]
If the automated cherry-pick had been successful, I think it would have cloned the bug for you, too. I think you'll have to do that by hand now, though to have a valid Jira ticket.

**Comment by dhellmann** [comment]
@jogeo do you have enough information to create a test plan for this PR?

**Comment by mangelajo** [comment]
> 

That was my next question, so I need to clone the JIRA ticket and target it to 4.12 I guess, let me try that. I am still not familiar enough to do it by heart.

**Comment by mangelajo** [comment]
@dhellmann but https://issues.redhat.com/browse/OCPBUGS-6860 is targeted to 4.12, do I need anything in addition to that?

**Comment by jogeo** [comment]
@dhellmann The original issue was easy to recreate and surfaced by a couple existing test cases. So, QE has the all the test plan information we need.

**Comment by dhellmann** [comment]
Thanks, @jogeo. Handing this off to QE, then.

/label backport-risk-assessed
/lgtm

**Pull request merged**
