### PR TITLE
OCPBUGS-12744: support all kustomization base filenames

### PR DESCRIPTION
**Pull request by dhellmann**
This change expands the search patterns for kustomization inputs to
include all of the forms supported by kubectl (kustomization.yaml,
kustomization.yml, and Kustomization).

### CODE REVIEW

**Comment by dhellmann** [comment]
@pacevedom you may want to look at this one, too. The second commit in the PR changes the kustomize test suite so that it only needs to restart MicroShift twice, which _significantly_ reduces the time it takes to run.

**Comment by eggfoobar** [comment]
LGTM thanks Doug! @pacevedom Feel free to slap the lgtm label once you've had a chance as well.

**Pull request merged**
