### PR TITLE
USHIFT-1726: Pull busybox from quay.io to avoid rate limit

### PR DESCRIPTION
**Pull request by dhensel-rh**
[USHIFT-1726](https://issues.redhat.com//browse/USHIFT-1726):
Needed because we are limited on the number of pulls

Closes #<Issue Number>

### CODE REVIEW

**Comment by pacevedom** [comment]
/retitle USHIFT-1726: Pull busybox from quay.io to avoid rate limit

**Review by pacevedom — APPROVED** [review]
/lgtm

**Comment by dhellmann** [comment]
@dhensel-rh you may want to try rebasing this now that some of the test stabilization fixes are in the main branch.

**Pull request merged**
