### PR TITLE
USHIFT-1780: Rebase lvms registry.access.redhat.com lvms4 lvms operator bundle v4.14.0-10

### PR DESCRIPTION
**Pull request by jakobmoellerdev**
**Which issue(s) this PR addresses**:

Rebases onto LVMS 4.14.0 which includes the latest published TopoLVM version of LVMS. Still contains sidecars for 4.13 but can be already tested as no regression is expected between 4.14.1 and 4.14.0

### CODE REVIEW

**Comment by jakobmoellerdev** [comment]
/hold
noticed that there are still some legacy artifacts in microshift managed resources, getting rid of those.

**Comment by jakobmoellerdev** [comment]
/unhold
verified no manifest changes in 4.13->4.14 however for 4.15 there will be multiple changes that require a little more effort.

**Comment by pmtk** [comment]
/retest

```
The compose result is empty.
```
([src](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_microshift/2496/pull-ci-openshift-microshift-main-microshift-metal-tests/1715338206796320768/artifacts/microshift-metal-tests/openshift-microshift-infra-iso-build/artifacts/build-logs/osbuild-rhel-9.2-microshift-4.14-edge-commit-a389bf0e-9605-4b1c-8cd8-19e4288a4092.log))

**Comment by jakobmoellerdev** [comment]
Are we good to go here or is something else required from me? (Just dont want to keep rebasing forever because of the nightly image updates)

**Pull request merged**
