### PR TITLE
OCPBUGS-36587: Filter ip family in router service controller

### PR DESCRIPTION
**Pull request by pacevedom**
**Which issue(s) this PR addresses**:

Closes #<Issue Number>

### CODE REVIEW

**Comment by pacevedom** [comment]
/hold
Need to rebase to main after https://github.com/openshift/microshift/pull/3579 merges

**Comment by ShudiLi** [comment]
/label qe-approved
```
1.
% oc get node                                                 
NAME                                             STATUS   ROLES                         AGE     VERSION
i-0398ce375a93861c5.us-west-2.compute.internal   Ready    control-plane,master,worker   8m27s   v1.30.2
% oc debug node/i-0398ce375a93861c5.us-west-2.compute.internal

2.
sh-5.1# ip address | grep "inet6 " | egrep -v "::1|fe80"
    inet6 2600:1f14:d19:8c00:ec8b:c697:5f1a:1b63/128 scope global dynamic noprefixroute 
sh-5.1# ip address | grep "inet " | egrep -v "127|169"
    inet 10.192.10.116/24 brd 10.192.10.255 scope global dynamic noprefixroute eth0
    inet 10.44.0.0/32 scope global br-ex
    inet 10.42.0.2/24 brd 10.42.0.255 scope global ovn-k8s-mp0
sh-5.1#

3.
% oc -n openshift-ingress get svc
NAME                      TYPE           CLUSTER-IP     EXTERNAL-IP                         PORT(S)                      AGE
router-default            LoadBalancer   10.43.10.173   10.192.10.116,10.42.0.2,10.44.0.0   80:30503/TCP,443:31130/TCP   9m19s
router-internal-default   ClusterIP      10.43.94.243   <none>                              80/TCP,443/TCP,1936/TCP      9m19s
%
```

**Review by pmtk — COMMENTED** [review]
/lgtm

**Pull request merged**
