### PR TITLE
USHIFT-2378: change sonobuoy command to match  the CNCF readme

### PR DESCRIPTION
**Pull request by eslutsky**
change the  sonobuoy invocation command to match the  [readme](https://github.com/cncf/k8s-conformance/blob/master/v1.27/rh-device-edge/README.md#run-conformance-tests)

### CODE REVIEW

**Comment by ggiguash** [comment]
@eslutsky , can you link the README in the PR description?

**Review by pacevedom — APPROVED** [review]
/lgtm

**Pull request merged**
