### PR TITLE
OPRUN-3064: OLM Update assets to include latest fixes

### PR DESCRIPTION
**Pull request by jmprusi**
Updates OLM assets to include latest fixes.

### CODE REVIEW

**Review by dhellmann — COMMENTED** [review]
/approve

This looks like a good change based on what we discussed on Slack. I'll leave it for @pmtk to lgtm so he has a chance to review, too.

**Comment by pmtk** [comment]
/override ci/prow/microshift-metal-tests ci/prow/ocp-conformance-rhel-eus ci/prow/ocp-conformance-rhel-eus-arm

**Pull request merged**
