### PR TITLE
NP-604: Loadbalancer Service document update

### PR DESCRIPTION
**Pull request by pliurh**
Update the document as we have a built-in loadbalancer controller in Microshift.

### CODE REVIEW

**Comment by ggiguash** [comment]
@pliurh, do you think there's a problem leaving both built-in and native LB procedures in this document?

I mean, can we stress the built-in LB and put the MetalLB instructions in a separate chapter in the end of the doc?

**Comment by pliurh** [comment]
> @pliurh, do you think there's a problem leaving both built-in and MetalLB procedures in this document?
> 
> I mean, can we stress the built-in LB and put the MetalLB instructions in a separate chapter in the end of the doc?

Currently, there is no configuration flag to turn off the built-in LB controller. There will be conflicts if we use Metal LB. So if there is still a requirement to use Metal LB on Microshift. We'll need to allow users to turn off the built-in LB controller.

**Comment by dhellmann** [comment]
> > @pliurh, do you think there's a problem leaving both built-in and MetalLB procedures in this document?
> > I mean, can we stress the built-in LB and put the MetalLB instructions in a separate chapter in the end of the doc?
> 
> Currently, there is no configuration flag to turn off the built-in LB controller. There will be conflicts if we use Metal LB. So if there is still a requirement to use Metal LB on Microshift. We'll need to allow users to turn off the built-in LB controller.

How does that work on OCP? Do we support multiple load balancers there?

@ggiguash do we know we need MetalLB support long term, or was that the approach for providing a load balancer until this work was done?

**Comment by pliurh** [comment]
> How does that work on OCP? Do we support multiple load balancers there?

For cloud platforms, there are built-in service controller implementations for each cloud provider. For on-prem platforms including baremetal, there is no built-in support in OCP. Metal-LB operator can be installed when needed. I don't think we prevent users from using other implementations as long as they are compatible with our CNIs. 

However, Microshift is special. The features supported by other LB implementations, such as VIP pool management, publishing the VIP on L2/L3, HA, etc, may not be useful in Microshift scenario.

**Comment by zshi-redhat** [comment]
> > @pliurh, do you think there's a problem leaving both built-in and MetalLB procedures in this document?
> > I mean, can we stress the built-in LB and put the MetalLB instructions in a separate chapter in the end of the doc?
> 
> Currently, there is no configuration flag to turn off the built-in LB controller. There will be conflicts if we use Metal LB. So if there is still a requirement to use Metal LB on Microshift. We'll need to allow users to turn off the built-in LB controller.

This is a good point. we shall provide an option to disable build-in load balancer.

**Comment by pliurh** [comment]
I proposed a PR to add the flag to turn the built-in loadbalancer controller off https://github.com/openshift/microshift/pull/1491.

**Comment by dhellmann** [comment]
/approve

Thank you for this, the documentation looks good. Maybe we can move the metallb procedure into a separate file and update it as part of #1491, so that knowledge is not lost?

**Comment by pliurh** [comment]
> /approve
> 
> Thank you for this, the documentation looks good. Maybe we can move the metallb procedure into a separate file and update it as part of #1491, so that knowledge is not lost?

Yeah, it makes sense.

**Pull request merged**
