### PR TITLE
USHIFT-3511: specify the ocp version when running check-payload

### PR DESCRIPTION
**Pull request by eslutsky**
**Which issue(s) this PR addresses**:

Closes #<Issue Number>

### CODE REVIEW

**Comment by eslutsky** [comment]
> This one needs [openshift/check-payload#202](https://github.com/openshift/check-payload/pull/202) right?

yes, waiting for the check-payload patch

**Comment by rphillips** [comment]
check-payload pr merged

/hold cancel

**Comment by ashwindasr** [comment]
@pacevedom @eslutsky the check payload pr (https://github.com/openshift/check-payload/pull/202) is not a blocker for using the `-V`. The patch is only to print out a warning if `-V` is not used and recommend users to do so.

**Comment by eslutsky** [comment]
/hold
this PR is affected by  libcrypto issue which is tracked here https://issues.redhat.com/browse/CMP-2639
 there is not fix for it yet.

**Comment by eslutsky** [comment]
/close
its fixed upstream, no longer needed.

**Pull request closed without merging**
