### PR TITLE
USHIFT-1859: Kustomization: enable server-side apply to avoid big resources failing

### PR DESCRIPTION
**Pull request by jmprusi**
Enables server-side apply for kustomize at startup. related to https://github.com/openshift/microshift/issues/2535

**Which issue(s) this PR addresses**:

Closes https://github.com/openshift/microshift/issues/2535

### CODE REVIEW

**Comment by dhellmann** [comment]
@jmprusi The change looks good, but we're going to want a jira ticket to ensure we get a release note for the new behavior. Can you work with @pacevedom to set that up, please?

/retest

**Comment by jmprusi** [comment]
@dhellmann I've updated the PR to properly maintain the old behavior to avoid issues with current microshift users. PTAL.

I will ping @pacevedom to get the proper Jira ticket created. 

Thanks.

**Comment by pacevedom** [comment]
/retitle USHIFT-1859: Kustomization: enable server-side apply to avoid big resources failing

**Review by pacevedom — APPROVED** [review]
/lgtm

**Pull request merged**
