### PR TITLE
[release-4.16] OCPBUGS-35814: Fix CRI-O version to match Kubernetes version

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by pmtk** [comment]
/test microshift-metal-tests

```
[MIRROR] cri-o-1.29.5-5.rhaos4.16.git7032128.el9.x86_64.rpm: Curl error (28): Timeout was reached for https://cdn.redhat.com/content/dist/layered/rhel9/x86_64/rhocp/4.16/os/Packages/c/cri-o-1.29.5-5.rhaos4.16.git7032128.el9.x86_64.rpm [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
(6/6): cri-o-1.29.5-5.rhaos4.16.git7032128.el9. 503 kB/s |  18 MB     00:37    
```
but it got installed

**Review by pacevedom — APPROVED** [review]
/lgtm

**Pull request merged**
