### PR TITLE
Disable non-MVP APIs

### LINKED ISSUE #633: [Enhancement]: Disable build, buildconfig controllers
#### What would you like to be added:

As they are now, builds consistently fail for several reasons related to how MicroShift has embedded and configured the API's respective controllers and due to some missing openshift operators.

For the time being, it would be best to disable the APIs until their value-add can be assessed within the scope of the project and the controllers' dependencies can be properly enabled.  

#### Why is this needed:

The build and buildConfig APIs are still advertised in the MicroShift API, which can and has lead users to assume they are supported.  As an accompanying #

### PR DESCRIPTION
**Pull request by copejon**
**Which issue(s) this PR addresses**:

Jira: [USHIFT-46](https://issues.redhat.com//browse/USHIFT-46)
Closes #633

### CODE REVIEW

**Comment by mangelajo** [comment]
lgtm, although it seems to need a rebase?

**Comment by fzdarsky** [comment]
@copejon tested it and it works nicely, thank you. In particular, it reduces the number of serviceaccounts (88 --> 51) and secrets (265 --> 54) significantly.

Just on question, please: Apart from the deployer and builder secrets, it also reduces the default-tokens from 2 to 1 and doesn't deploy the default-dockercfg tokens anymore. Are they not needed / what were they used for?

**Comment by oglok** [comment]
These are the available apiservices with this PR:

```
[root@fedora ~] # oc get apiservices.apiregistration.k8s.io -w
NAME                                   SERVICE                             AVAILABLE   AGE
v1.                                    Local                               True        20s
v1.admissionregistration.k8s.io        Local                               True        20s
v1.apiextensions.k8s.io                Local                               True        20s
v1.apps                                Local                               True        20s
v1.authentication.k8s.io               Local                               True        20s
v1.authorization.k8s.io                Local                               True        20s
v1.authorization.openshift.io          Local                               True        8s
v1.autoscaling                         Local                               True        20s
v1.batch                               Local                               True        20s
v1.certificates.k8s.io                 Local                               True        20s
v1.coordination.k8s.io                 Local                               True        20s
v1.discovery.k8s.io                    Local                               True        20s
v1.events.k8s.io                       Local                               True        20s
v1.networking.k8s.io                   Local                               True        20s
v1.node.k8s.io                         Local                               True        20s
v1.policy                              Local                               True        20s
v1.project.openshift.io                default/openshift-apiserver         True        3s
v1.rbac.authorization.k8s.io           Local                               True        20s
v1.route.openshift.io                  default/openshift-apiserver         True        3s
v1.scheduling.k8s.io                   Local                               True        20s
v1.security.openshift.io               Local                               True        13s
v1.storage.k8s.io                      Local                               True        20s
v1.user.openshift.io                   default/openshift-oauth-apiserver   True        3s
v1beta1.batch                          Local                               True        20s
v1beta1.discovery.k8s.io               Local                               True        20s
v1beta1.events.k8s.io                  Local                               True        20s
v1beta1.flowcontrol.apiserver.k8s.io   Local                               True        20s
v1beta1.node.k8s.io                    Local                               True        20s
v1beta1.policy                         Local                               True        20s
v1beta1.storage.k8s.io                 Local                               True        20s
v1beta2.flowcontrol.apiserver.k8s.io   Local                               True        20s
v2.autoscaling                         Local                               True        20s
v2beta1.autoscaling                    Local                               True        20s
v2beta2.autoscaling                    Local                               True        20s
```

After addressing Frank's questions, It's good to be merged.

**Comment by fzdarsky** [comment]
Couldn't find anything not working without the duplicate $namespace-tokens and $namespace-dockercfg.

/lgtm

**Review by fzdarsky — APPROVED** [review]

**Pull request merged**
