### PR TITLE
USHIFT-2157: Upgrade osbuild copr package versions after copr cleanup

### PR DESCRIPTION
**Pull request by ggiguash**

### CODE REVIEW

**Comment by dhellmann** [comment]
Lots of failures in the ARM job. It looks like a greenboot failure.

```
Job for greenboot-healthcheck.service failed because the control process exited with error code.\nSee "systemctl status greenboot-healthcheck.service" and "journalctl -xeu greenboot-healthcheck.service" for details.
```

Let's see if it's a flake.

/lgtm

**Comment by dhellmann** [comment]
> Lots of failures in the ARM job. It looks like a greenboot failure.
> 
> ```
> Job for greenboot-healthcheck.service failed because the control process exited with error code.\nSee "systemctl status greenboot-healthcheck.service" and "journalctl -xeu greenboot-healthcheck.service" for details.
> ```
> 
> Let's see if it's a flake.
> 
> /lgtm

```
40_microshift_running_check.sh[10024]: Error: Timed out waiting for 2 pod(s) in the 'openshift-storage' namespace to be in 'Ready' state
```

**Comment by ggiguash** [comment]
We're experiencing "known" problem with MicroShift service not responding after frequent restarts.
/override ci/prow/microshift-metal-tests-arm

**Pull request merged**
