### PR TITLE
Update the devenv documentation with pprof instructions

### PR DESCRIPTION
**Pull request by ggiguash**
Document #836 work, binding `pprof` server to the public hostname to allow remote access to the profile data.
Closes [USHIFT-254](https://issues.redhat.com//browse/USHIFT-254)

### CODE REVIEW

**Comment by zshi-redhat** [comment]
LGTM

**Comment by ggiguash** [comment]
The executable size reduction is 150MB vs 115MB when CGO is disabled.

MicroShift executable build with CGO support
```
$ ldd microshift 
        linux-vdso.so.1 (0x00007fff529f7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb7e7fcb000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb7e7dab000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb7e79e6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb7e81cf000)
$ ls -l microshift 
-rwxrwxr-x. 1 microshift microshift 151104128 Aug  7 08:42 microshift
```

MicroShift executable built without CGO support
```
$ ldd microshift 
        not a dynamic executable
$ ls -l microshift 
-rwxrwxr-x. 1 microshift microshift 119431168 Aug  8 01:33 microshift
```

**Review by mangelajo — COMMENTED** [review]
/lgtm

**Pull request merged**
