### PR TITLE
USHIFT-3144: Obsolete scripts/image-builder directory and build.sh script

### PR DESCRIPTION
**Pull request by ggiguash**
This PR addresses the following issues:
- [USHIFT-3146](https://issues.redhat.com//browse/USHIFT-3146)
- [USHIFT-3147](https://issues.redhat.com//browse/USHIFT-3147)
- [USHIFT-3148](https://issues.redhat.com//browse/USHIFT-3148)
- [USHIFT-3145](https://issues.redhat.com//browse/USHIFT-3145)

Note that there are also 2 documentation related fixes that will need to be reviewed in the context of global repository documentation review epic. Currently, added `TODO` statements in the existing documents.

### CODE REVIEW

**Comment by ggiguash** [comment]
Subscription issues.
/test e2e-aws-tests-arm e2e-aws-tests-periodic-arm

**Comment by pmtk** [comment]
This looks good to me. Is QE aware of this? I think they consuming these scripts

**Comment by ggiguash** [comment]
> This looks good to me. Is QE aware of this? I think they're consuming these scripts

We got approval from QE on Slack. See https://redhat-internal.slack.com/archives/C03CJTNLKAT/p1720633827078309

**Comment by ggiguash** [comment]
/testwith openshift/microshift/obsolete_image_builder/e2e-aws-tests #4141

**Comment by ggiguash** [comment]
/testwith openshift/microshift/obsolete_image_builder/e2e-aws-tests openshift/microshift#4141

**Comment by ggiguash** [comment]
/testwith openshift/microshift/main/e2e-aws-tests openshift/microshift#4141 openshift/microshift#4127

**Comment by ggiguash** [comment]
The failure has nothing to do with the PR changes. Overriding to save CI cycles.
/override ci/prow/e2e-aws-tests

**Pull request merged**
