### PR TITLE
Revert "microshift: compact ovn databases periodically"

### PR DESCRIPTION
**Pull request by mangelajo**
This reverts commit a81d1d39b4093cbd142db166c7f5949ff71afd00.

Closes-Issue: https://issues.redhat.com/browse/USHIFT-451

### CODE REVIEW

**Comment by mangelajo** [comment]
We need to find a different way to do compaction, the readiness probe is not the right place.

**Comment by zshi-redhat** [comment]
> We need to find a different way to do compaction, the readiness probe is not the right place.

I agree, thanks for the fix @mangelajo !
/lgtm

**Comment by mangelajo** [comment]
> > We need to find a different way to do compaction, the readiness probe is not the right place.
> 
> I agree, thanks for the fix @mangelajo ! /lgtm

Thanks for having an eye on it zshi! :D

**Pull request merged**
