### PR TITLE
[release-4.14] OCPBUGS-36478: Set CRI-O version to match Kubernetes' version

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Review by pacevedom — COMMENTED** [review]
/lgtm

**Comment by pmtk** [comment]
```
  1293  Jul 03 04:18:19 el92-prel-upgrade-block-2minor-host1 ovs-ctl[1008]: ovsdb-server: (null): Invalid --user option openvswitch:hugetlbfs (user openvswitch is not in group hugetlbfs), aborting.
      1 Jul 03 04:18:19 el92-prel-upgrade-block-2minor-host1 ovs-ctl[953]: Starting ovsdb-server ... failed!
      2 Jul 03 04:18:19 el92-prel-upgrade-block-2minor-host1 systemd[1]: ovsdb-server.service: Control process exited, code=exited, status=1/FAILURE
      3 Jul 03 04:18:19 el92-prel-upgrade-block-2minor-host1 systemd[1]: ovsdb-server.service: Failed with result 'exit-code'.
      4 Jul 03 04:18:19 el92-prel-upgrade-block-2minor-host1 systemd[1]: Failed to start Open vSwitch Database Unit.
      5 Jul 03 04:18:19 el92-prel-upgrade-block-2minor-host1 systemd[1]: Dependency failed for Open vSwitch Forwarding Unit.
      6 Jul 03 04:18:19 el92-prel-upgrade-block-2minor-host1 systemd[1]: Dependency failed for Open vSwitch.
      7 Jul 03 04:18:19 el92-prel-upgrade-block-2minor-host1 systemd[1]: Dependency failed for Configures Open vSwitch for OVN (MicroShift).
      8 Jul 03 04:18:19 el92-prel-upgrade-block-2minor-host1 systemd[1]: icroshift-ovs-init.service: Job microshift-ovs-init.service/start failed with result 'dependency'.
```

**Pull request merged**
