### PR TITLE
NO-ISSUE: Add JIRA bug trend generator

### PR DESCRIPTION
**Pull request by pacevedom**
**Which issue(s) this PR addresses**:

Closes #<Issue Number>

### CODE REVIEW

**Comment by dhellmann** [comment]
Doesn't Jira have built-in tools for producing these sorts of graphs?

**Comment by pacevedom** [comment]
> Doesn't Jira have built-in tools for producing these sorts of graphs?

Yes, but we have an issue with that. JIRA produces these charts using the resolution field, which in our case does not transition to Done until errata takes over and includes the bug in an advisory. In other words, charts lag until automation kicks in.
This happens quite late, so JIRA charts don't show the current situation for the team. What this tool does instead is take the transition of the status to verified as another measure for classifying the issue as resolved. Once an issue is in that status, the team does not need any further involvement.

**Comment by dhellmann** [comment]
> > Doesn't Jira have built-in tools for producing these sorts of graphs?
> 
> Yes, but we have an issue with that. JIRA produces these charts using the resolution field, which in our case does not transition to Done until errata takes over and includes the bug in an advisory. In other words, charts lag until automation kicks in. This happens quite late, so JIRA charts don't show the current situation for the team. What this tool does instead is take the transition of the status to verified as another measure for classifying the issue as resolved. Once an issue is in that status, the team does not need any further involvement.

We can edit those filters in Jira.

**Comment by pacevedom** [comment]
Close for now. If we need something not supported in JIRA we can bring it up again.

**Pull request closed without merging**
