### PR TITLE
USHIFT-583: add script for generating API docs

### PR DESCRIPTION
**Pull request by dhellmann**
Set up a docker container to run the openshift-apdocs-gen tool and a
script to wrap it to use the container to generate documentation for
MicroShift.

See https://github.com/openshift/openshift-docs/pull/55564 for an example of the output.

### CODE REVIEW

**Comment by dhellmann** [comment]
/retitle USHIFT-583: add script for generating API docs

**Comment by dhellmann** [comment]
Jason, this is what I came up with for automating API docs for MicroShift, please take a look when you have a minute.

/cc @jboxman-rh

**Comment by jboxman-rh** [comment]
@dhellmann, LGTM

**Comment by dhellmann** [comment]
/hold

Let's wait until the docs PR passes the build tests

**Comment by dhellmann** [comment]
This is not ready to land, so I'm closing the PR to clear some of the review board. I'll reopen when we have a new owner for the work.

/close

**Pull request closed without merging**
