### PR TITLE
NO-ISSUE: Fix spelling error in getting started docs

### PR DESCRIPTION
**Pull request by larsks**
Change "optionated" to "opinionated" in `getting_started.md`.

### CODE REVIEW

**Comment by ggiguash** [comment]
@larsks , thank you for this PR.
Can you double-check the uploaded file? For some reason, it is recognized as a BIN type, so we cannot merge this change as-is currently.

**Comment by ggiguash** [comment]
/retitle NO-ISSUE: Fix spelling error in getting started docs

**Comment by dhellmann** [comment]
There is a null byte at the start of the file committed in this PR that isn't present in the file in the main branch.

**Comment by larsks** [comment]
Fixed. Somehow that snuck in using the in-browser editor.

**Review by dhellmann — COMMENTED** [review]
/lgtm

Thanks!

**Pull request merged**
