### PR TITLE
USHIFT-717: Remove IPs from certificates

### PR DESCRIPTION
**Pull request by pacevedom**
**Which issue(s) this PR addresses**:

Closes #<Issue Number>

### CODE REVIEW

**Comment by dhellmann** [comment]
@pacevedom could you add some detail about why we want to do this?

**Comment by pacevedom** [comment]
> @pacevedom could you add some detail about why we want to do this?

IPs in certificates were not being used and this PR enables the removal of the MicroShift automatic reset when the node IP changes (but this is not included here).
It also provides an easier handling/reasoning of certificates relying only on hostnames and DNS.
Need to create a JIRA ticket for all this if the PR is accepted, as there will be (at least) another one.

**Comment by dhellmann** [comment]
> > @pacevedom could you add some detail about why we want to do this?
> 
> IPs in certificates were not being used and this PR enables the removal of the MicroShift automatic reset when the node IP changes (but this is not included here). It also provides an easier handling/reasoning of certificates relying only on hostnames and DNS. Need to create a JIRA ticket for all this if the PR is accepted, as there will be (at least) another one.

Does this add an expectation that DNS is always configured? Or pre-configured? I'm not sure we can count on that in all settings.

**Comment by ggiguash** [comment]
This is a 4.13 task, so putting it on hold until 4.12 branch is created.
/hold

**Review by mangelajo — COMMENTED** [review]
/approve

I like this. We completely decouple from NodeIP everywhere.

**Comment by dhellmann** [comment]
@pacevedom based on https://github.com/openshift/enhancements/pull/1320 we no longer want this, right?

**Comment by dhellmann** [comment]
The changes look OK, but CI doesn't seem very happy.

**Comment by pmtk** [comment]
Maybe changing https://github.com/openshift/microshift/blob/main/pkg/controllers/etcd.go#L152 will help?

**Pull request merged**
