### PR TITLE
USHIFT-3319: Re-Enable Non-Upgrade Scenarios Which Depend on 4.17 mirrored rpms

### PR DESCRIPTION
**Pull request by copejon**
Upgrade tests are handled by PR #3506

### CODE REVIEW

**Comment by copejon** [comment]
FIPs scenarios are currently broken. See this PR's jira ticket for more information

**Comment by copejon** [comment]
Waiting for #3505 to unblock the periodics

**Comment by ggiguash** [comment]
/lgtm
/override ci/prow/metal-periodic-test
The tests fail with FIPS errors which is a known problem.

**Pull request merged**
