### PR TITLE
USHIFT-2068: Implement retries on failed skopeo in mirror-images.sh

### PR DESCRIPTION
**Pull request by ggiguash**

### CODE REVIEW

**Review by pacevedom — APPROVED** [review]
/ lgtm

**Review by pacevedom — COMMENTED** [review]
/lgtm

**Comment by ggiguash** [comment]
The failure is due to non-existing cache of containers on ARM platform.
/override ci/prow/microshift-metal-tests-arm

**Comment by ggiguash** [comment]
/override ci/prow/microshift-metal-tests-arm
Greenboot failure due to lack of local container cache on ARM

**Pull request merged**
