### PR TITLE
Document supported OpenShift APIs

### PR DESCRIPTION
**Pull request by copejon**
**Which issue(s) this PR addresses**:

[USHIFT-47](https://issues.redhat.com//browse/USHIFT-47)

### CODE REVIEW

**Review by sallyom — APPROVED** [review]
lgtm

**Comment by oglok** [comment]
```
podsecuritypolicyreviews                           security.openshift.io/v1               true         PodSecurityPolicyReview
podsecuritypolicyselfsubjectreviews                security.openshift.io/v1               true         PodSecurityPolicySelfSubjectReview
podsecuritypolicysubjectreviews                    security.openshift.io/v1               true         PodSecurityPolicySubjectReview
rangeallocations                                   security.openshift.io/v1               false        RangeAllocation

```

These APIs should not be exposed in MicroShift, and indeed, they were not in 4.8. It's all related to the inclusion of an API service for the security API group, that also causes the SCCs to fail. Related to this PR: #739

**Review by dhellmann — APPROVED** [review]

**Pull request merged**
