### PR TITLE
Rebase lvms registry.redhat.io lvms4 lvms operator bundle v4.17.0 43

### PR DESCRIPTION
**Pull request by eggfoobar**
**Which issue(s) this PR addresses**:
 
LVMS 4.17.0 GA

### CODE REVIEW

**Comment by copejon** [comment]
Looks like the version fix did the trick!

/lgtm

**Comment by ggiguash** [comment]
/retitle OCPBUGS-41214: Rebase lvms registry.redhat.io lvms4 lvms operator bundle

**Pull request merged**
