### PR TITLE
USHIFT-1049 QE: regression case failure [sig-storage] STORAGE MicroShiftOnly-Author:rdeore-Critical-59660-[MicroShift] Volumes resize on-line

### PR DESCRIPTION
**Pull request by copejon**
**Which issue(s) this PR addresses**:

Closes [USHIFT-1049](https://issues.redhat.com//browse/USHIFT-1049)

### CODE REVIEW

**Comment by dhellmann** [comment]
It looks like this is missing the updates to the list of assets. 

Is the startup code already trying to load the manifests, or do we need changes there, too?

**Comment by dhellmann** [comment]
/retest

It would be good to have at least a smoke test for this before we merge it. Maybe that means we wait for the RF job to exist?

**Comment by copejon** [comment]
misfired a push that deleted the remote branch, reopening

**Review by dhellmann — COMMENTED** [review]
/lgtm

**Pull request merged**
