### PR TITLE
USHIFT-793: add a script to automatically produce EC release notes

### PR DESCRIPTION
**Pull request by dhellmann**
This script partially automates the process of publishing release
notes for engineering candidates.

### CODE REVIEW

**Comment by dhellmann** [comment]
https://github.com/openshift/microshift/releases/tag/4.13.0-ec-3 was created using this script.

**Comment by dhellmann** [comment]
Transposed the digits in the ticket ID at first. This is related to USHIFT-793.

**Comment by pmtk** [comment]
Looks very nice, I like the result (release tag on GH).
Hold in case you want others to look at this, otherwise unhold.

/lgtm
/hold

**Pull request merged**
