### PR TITLE
USHIFT-2012: convert http access to use built-in instead of curl

### PR DESCRIPTION
**Pull request by dhellmann**
There's no need to shell out to curl when making a web request from
the test suite.

/assign @copejon

### CODE REVIEW

**Comment by dhellmann** [comment]
subscription manager error: OSError: [Errno 107] Transport endpoint is not connected

/retest

**Comment by copejon** [comment]
The x86_64 metal tests is still seeing the [flake](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_microshift/2706/pull-ci-openshift-microshift-main-microshift-metal-tests/1733987716560850944). I'm closing PRs related to the issue to since we've got a number of them open now.

**Pull request closed without merging**
