### PR TITLE
Start using RHEL 9.2 in the devenv and edge

### PR DESCRIPTION
**Pull request by ggiguash**
* Switch the development environment to use RHEL 9.2 beta
* Enable osbuild configuration to use RHEL 9.2 beta channels
* Use golang that comes with the OS
* Fix the golang dependency in the MicroShift RPM spec file

Closes:
* [USHIFT-1023](https://issues.redhat.com//browse/USHIFT-1023)
* [OCPBUGS-10472](https://issues.redhat.com//browse/OCPBUGS-10472)

### CODE REVIEW

**Comment by ggiguash** [comment]
OCPBUGS-10472

**Comment by dhellmann** [comment]
Are we confident about committing to a move to a beta version of the OS? I'd feel more comfortable making this optional so we can still develop easily on 9.1 if we have to.

**Comment by ggiguash** [comment]
> Are we confident about committing to a move to a beta version of the OS? I'd feel more comfortable making this optional so we can still develop easily on 9.1 if we have to.

I think we may want to try it and roll back in case there is a stopper issue. It's the OS used for OCP 4.13, so it should also be stable enough for MicroShift.

**Comment by dhellmann** [comment]
The test just passed and then failed again.

/override ci/prow/e2e-reboot

**Pull request merged**
