### PR TITLE
[release-4.15] OCPBUGS-29281: Rebase lvms registry.access.redhat.com lvms4 lvms operator bundle v4.15.0

### PR DESCRIPTION
**Pull request by jakobmoellerdev**
**Which issue(s) this PR addresses**:

backports the introduction of LVMS 4.15.0 without the Architecture change to release-4.15.

Closes #<Issue Number>

### CODE REVIEW

**Comment by ggiguash** [comment]
/retitle [release-4.15] OCPBUGS-29281: Rebase lvms registry.access.redhat.com lvms4 lvms operator bundle v4.15.0

**Comment by ggiguash** [comment]
@jogeo , as discussed, adding Eng labels and delegating final approval to QE.

/label backport-risk-assessed
/lgtm
/label jira/valid-issue

**Comment by radeore** [comment]
Pre-merge testing done on x86 and ARM clusters, storage test run Passed.

**Pull request merged**
