### PR TITLE
USHIFT-1244: Start using RHEL 9.2 repositories for devenv and image builder

### PR DESCRIPTION
**Pull request by dhellmann**
Manual backport of #1789 

/assign @ggiguash

### CODE REVIEW

**Comment by dhellmann** [comment]
```
sudo subscription-manager repos --enable rhocp-4.12-for-rhel-9-x86_64-rpms --enable fast-datapath-for-rhel-9-x86_64-rpms
Error: 'fast-datapath-for-rhel-9-x86_64-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
Repository 'rhocp-4.12-for-rhel-9-x86_64-rpms' is enabled for this system.
```

@ggiguash @pacevedom do either of you have any idea why that step is failing in the conformance job in the 4.13 branch?

**Comment by ggiguash** [comment]
Looks like we were using a wrong image. Should be fixed in https://github.com/openshift/release/pull/39256.
Rerunning tests.

/retest

**Review by pacevedom — COMMENTED** [review]
/label cherry-pick-approved

**Pull request merged**
