### PR TITLE
Use OpenShift Infra NS from KCM operator

### PR DESCRIPTION
**Pull request by oglok**
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>

The `openshift-infra` namespace is now gathered from the `cluster-kube-controller-manager-operator` assets.

### CODE REVIEW

**Comment by dhellmann** [comment]
I see the asset being updated, but I don't see a change to the rebase script. What causes the manifest to come from the KCM operator?

**Comment by oglok** [comment]
> I see the asset being updated, but I don't see a change to the rebase script. What causes the manifest to come from the KCM operator?

Good catch, I always forget about updating the rebase script. Done!

**Comment by dhellmann** [comment]
/close

See #890 instead

**Pull request closed without merging**
