### PR TITLE
USHIFT-2139: bump sonobuoy version to 0.57.1

### PR DESCRIPTION
**Pull request by eslutsky**
**Which issue(s) this PR addresses**:

Closes #<Issue Number>

### CODE REVIEW

**Review by pacevedom — COMMENTED** [review]
/lgtm

**Comment by ggiguash** [comment]
The failure is on the "known" problem unrelated to the change.
/override ci/prow/metal-periodic-test-arm

**Comment by ggiguash** [comment]
The CNCF test passed and the failure is not related to the current change. 
/override ci/prow/metal-periodic-test

**Pull request merged**
