### PR TITLE
USHIFT-521: Fix ART builds; bring back golang in microshift.spec

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by pmtk** [comment]
```
$ go version
go version go1.18.7 linux/amd64

$ whereis go
go: /usr/bin/go /usr/local/bin/go

$ echo $PATH
/home/microshift/.local/bin:/home/microshift/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin

$ /usr/bin/go version
go version go1.17.12 linux/amd64

$ /usr/local/bin/go version
go version go1.18.7 linux/amd64
```

**Review by mangelajo — COMMENTED** [review]
/lgtm

**Pull request merged**
