### PR TITLE
USHIFT-1861: Fix network smoke tests flakes

### PR DESCRIPTION
**Pull request by pacevedom**
**Which issue(s) this PR addresses**:

Closes #<Issue Number>

### CODE REVIEW

**Comment by pmtk** [comment]
As a general idea I'd prefer to make sure tests leave clean environment on teardown, rather than next test making sure of that but for now looks good to me

/lgtm

**Comment by pacevedom** [comment]
Metal test failed because this change was not yet merged: https://github.com/openshift/microshift/pull/2725

/test microshift-metal-tests

**Comment by pacevedom** [comment]
Overriding the rebase as the failure relates to a patch that needs an update and that is handled in a different PR.

/override ci/prow/test-rebase

**Pull request merged**
