### PR TITLE
USHIFT-3136: Increase nginx resources and timeouts to mitigate failed ostree installations

### PR DESCRIPTION
**Pull request by ggiguash**

### CODE REVIEW

**Comment by pacevedom** [comment]
/override ci/prow/metal-periodic-test
/override ci/prow/metal-periodic-test-arm
Overriding because this change does not impact the failing tests and we need the change for nightly builds asap.

**Review by pacevedom — APPROVED** [review]
/lgtm

**Comment by ggiguash** [comment]
OVerriding the bootc tests to save on CI cycles. The failures are not related to the current change - VM stuck on reboot (known problem).
/override ci/prow/metal-bootc-test ci/prow/metal-bootc-test-arm

**Comment by ggiguash** [comment]
/override ci/prow/metal-periodic-test ci/prow/metal-periodic-test-arm ci/prow/microshift-metal-tests 
ci/prow/microshift-metal-tests-arm

**Pull request merged**
