### PR TITLE
USHIFT-4547: Add timeout and retries to ISO downloads when building images

### PR DESCRIPTION
**Pull request by ggiguash**
Also fixed wrong job count in the parallel command options. Each job parameters are added in quotes, which means 1 parameter per job for count, not 2. Before the fix, the `--jobs 0` argument was used due to `1 / 2 = 0`.

```
    download_opts+=("${expected_iso_file} ${download_url}")
```

Comparing wget and aria2 download speeds on a local workstation.
```
$ time wget -O centos9-wget.iso "https://mi
rrors.centos.org/mirrorlist?path=/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-late
st-x86_64-dvd1.iso&redirect=1&protocol=https"
centos9-wget.iso     100% [==============================>]   10.79G   31.09MB/s
                          [Files: 1  Bytes: 10.79G [31.51M]

real    5m50.796s
user    0m5.486s
sys     0m16.325s

$ time aria2c -x 4 -s 4 -o centos9-aria2.is
o "https://mirrors.centos.org/mirrorlist?path=/9-stream/BaseOS/x86_64/iso/CentOS-
Stream-9-latest-x86_64-dvd1.iso&redirect=1&protocol=https"
...
...

real    2m52.656s
user    0m6.979s
sys     0m13.922s
```

### CODE REVIEW

**Comment by ggiguash** [comment]
Deleted the cache in AWS S3 bucket on x86 platform.
/test e2e-aws-tests-cache

**Comment by ggiguash** [comment]
```
+ 16:21:27.203856205 ./bin/build_images.sh:665 	'[' '!' -f /home/ec2-user/microshift/_output/bin/gomplate ']'
+ 16:21:27.204686892 ./bin/build_images.sh:666 	/home/ec2-user/microshift/scripts/fetch_tools.sh gomplate
Installing gomplate to /home/ec2-user/microshift/_output/bin
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
```

/test e2e-aws-tests-cache

**Comment by ggiguash** [comment]
The cache creation test [passed successfully](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_microshift/3997/pull-ci-openshift-microshift-main-e2e-aws-tests-cache/1842974028524949504/artifacts/e2e-aws-tests-cache/openshift-microshift-infra-iso-build/build-log.txt) using aria2c executable for downloading ISO.

The PR is ready for review.

**Review by pacevedom — APPROVED** [review]
/lgtm

**Pull request merged**
