### PR TITLE
OCPBUGS-22338: Add base etcd version output to microshift-etcd

### PR DESCRIPTION
**Pull request by ggiguash**
The output was modeled after `microshift version` command with its `Base...` notion.
```
$ ./microshift version
MicroShift Version: 4.15.0-0.nightly-2023-11-20-004519-20231121080816-4c70581df-dirty
Base OCP Version: 4.15.0-0.nightly-2023-11-20-004519

$ ./microshift-etcd version
MicroShift-etcd Version: 4.15.0-0.nightly-2023-11-20-004519-20231121080816-4c70581df-dirty
Base etcd Version: 3.5.10
```

The full output now presents `etcdVersion` new field
```
$ ./microshift-etcd version -o json
{
  "major": "4",
  "minor": "15",
  "gitVersion": "4.15.0-0.nightly-2023-11-20-004519-20231121080816-4c70581df-dirty",
  "gitCommit": "4c70581df",
  "gitTreeState": "dirty",
  "buildDate": "2023-11-21T11:54:57Z",
  "goVersion": "go1.20.10",
  "compiler": "gc",
  "platform": "linux/amd64",
  "patch": "0",
  "etcdVersion": "3.5.10"
}
```
The version information is also printed in the `microshift-etcd` logs
```
I1121 14:41:27.455098  174144 run.go:111] "Version" microshift-etcd="4.15.0-0.nightly-2023-11-20-004519-20231121115627-79ea2b86d-dirty" etcd-base="3.5.10"
```
/cc @sjug 
/cc @pmtk

### CODE REVIEW

**Comment by pmtk** [comment]
Looks nice. I have suggestion to also print these versions on startup, similar to what we have here: https://github.com/openshift/microshift/blob/main/pkg/cmd/run.go#L63-L64

**Comment by ggiguash** [comment]
> Looks nice. I have suggestion to also print these versions on startup, similar to what we have here: https://github.com/openshift/microshift/blob/main/pkg/cmd/run.go#L63-L64

@pmtk , I uploaded another commit and updated the PR description with a sample output. 
Is this what you had in mind?

**Comment by sjug** [comment]
/lgtm

Tested and working as expected.

**Comment by ggiguash** [comment]
The test failure has nothing to do with the etcd changes. It's a "known" problem in the Networking suite
/override microshift-metal-cache

**Comment by ggiguash** [comment]
The test failure has nothing to do with the etcd changes. It's a "known" problem in the Networking suite
/override metal-periodic-test

**Comment by ggiguash** [comment]
/override pull-ci-openshift-microshift-main-metal-periodic-test

**Comment by ggiguash** [comment]
/override pull-ci-openshift-microshift-main-microshift-metal-cache

**Pull request merged**
