### PR TITLE
USHIFT-1111: Remove kuttl (`validate-microshift/`)

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by copejon** [comment]
Is there an openshift/release side PR that removes the dependency on validate-microshift?

**Comment by pmtk** [comment]
Removal of refs to `validate-microshift/` from relevant CI configs: https://github.com/openshift/release/pull/42516

**Comment by ggiguash** [comment]
Looks good. Feel free to unhold once all tests pass.
/lgtm
/hold

**Pull request merged**
