### PR TITLE
USHIFT-552: Rebase with K8s 1.26

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by pmtk** [comment]
Does not compile yet:
```
# github.com/openshift/route-controller-manager/pkg/route/ingress
vendor/github.com/openshift/route-controller-manager/pkg/route/ingress/ingress.go:545:48: cannot use ingressIngresses (variable of type []"k8s.io/api/core/v1".LoadBalancerIngress) as type []"k8s.io/api/networking/v1".IngressLoadBalancerIngress in assignment
```

I believe we need https://github.com/openshift/route-controller-manager/pull/15 ([specifically](https://github.com/openshift/route-controller-manager/pull/15/files#diff-5100b0e98310cb270f5b9b2bc09313e46cdb9c509eef0ea3a76dda2a07ce987b))

**Comment by pmtk** [comment]
/hold
TODO: `s/golang_version 1.18/golang_version 1.19/` in `packaging/rpm/microshift.spec`

**Comment by dhellmann** [comment]
Also related to OCPBUGS-3534

**Pull request merged**
