### PR TITLE
[release-4.18] OCPBUGS-47463: Raise the default greenboot timeout to 600s

### PR DESCRIPTION
**Pull request by ggiguash**
Manual cherry-pick of https://github.com/openshift/microshift/pull/4340 due to bootc test structure changes.

### CODE REVIEW

**Comment by ggiguash** [comment]
The following failure seems to be related to the https://github.com/openshift/microshift/pull/4338 fix.

```
+ 17:18:40.399471162 ./bin/scenario.sh:953 	timeout -v --kill-after=5m 30m /home/ec2-user/microshift/_output/robotenv/bin/robot --name cos9-src@standard-suite2 --randomize all --loglevel TRACE --outputdir /home/ec2-user/microshift/_output/test-images/scenario-info/cos9-src@standard-suite2 --debugfile /home/ec2-user/microshift/_output/test-images/scenario-info/cos9-src@standard-suite2/rf-debug.log -x junit.xml -V /home/ec2-user/microshift/_output/test-images/scenario-info/cos9-src@standard-suite2/variables.yaml suites/standard2
...
...
timeout: sending signal TERM to command ‘/home/ec2-user/microshift/_output/robotenv/bin/robot’
Second signal will force exit.
timeout: sending signal KILL to command ‘/home/ec2-user/microshift/_output/robotenv/bin/robot’
./bin/scenario.sh: line 867: 319286 Killed                  ${timeout_robot} --name "${SCENARIO}" --randomize "${TEST_RANDOMIZATION}" --loglevel TRACE --outputdir "${SCENARIO_INFO_DIR}/${SCENARIO}" --debugfile "${SCENARIO_INFO_DIR}/${SCENARIO}/rf-debug.log" -x junit.xml ${var_arg} "$@"
+ 17:53:40.403659756 ./bin/scenario.sh:962 	'[' 0 -ge 124 ']'
+ 17:53:40.404982764 ./bin/scenario.sh:965 	return 1
```

**Review by pacevedom — APPROVED** [review]
/lgtm
/label backport-risk-assessed
/label cherry-pick-approved

**Pull request merged**
