### PR TITLE
USHIFT-1751: Add role to run kube-burner workloads

### PR DESCRIPTION
**Pull request by sjug**
**Which issue(s) this PR addresses**:
Closes #[USHIFT-1751](https://issues.redhat.com//browse/USHIFT-1751)

### CODE REVIEW

**Comment by agullon** [comment]
Hi @sjug, I found a few issues when running it:
* Failed to start because host name is not valid
   * This is the same issue I found when running `run-perf.yml` weeks ago
      * https://github.com/openshift/microshift/pull/2284#issuecomment-1735065440 
   * workaround:
      * on ansible/setup-node.yml set hosts variable in lines 10 and 31 to microshift-dev
* The role 'quick-microshift-boot' was not found
   * The error appears to be in '/home/microshift/microshift/ansible/setup-node.yml': line 81, column 7, but may be elsewhere in the file depending on the exact syntax problem.
   * workaround:
      * remove this task because I couldn’t find in the repo any reference to quick-microshift-boot role
* TASK [fetch-kubeconfig : create .kube folder in home directory if missing]
   * "The conditional check 'not kubeconfig_directory_check.stat.isdir' failed. The error was: error while evaluating conditional (not kubeconfig_directory_check.stat.isdir): 'dict object' has no attribute 'isdir'.
   * workaround
      * add additional condition to check  if folder exists before checking if is a directory on ansible/roles/fetch-kubeconfig/tasks/main.yml:19
* TASK [setup-localhost : ansible.builtin.command] 
   * fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_user' is undefined. 'ansible_user' is undefined\n\nThe error appears to be in '/home/microshift/jenkins-microshift-microshift-create-buildvm-3926/ansible/roles/setup-localhost/tasks/main.yml'
   * workaround
      * add manually the remote hostname in ansible/roles/fetch-kubeconfig/defaults/main.yml:6
* TASK [run-workloads : extract kube-burner files] 
   * An exception occurred during task execution. fatal: [localhost]: FAILED! => {"changed": false, "msg": "dest '/home/microshift/.local/bin' must be an existing dir"}
   * few tasks before that directory was found because it’s in the PATH
   * workaround:
      * created manually in the ansible host the directory /home/microshift/.local/bin that only existed in the PATH

**Comment by agullon** [comment]
I got this error when running it (applying workaround from my previous comment https://github.com/openshift/microshift/pull/2455#issuecomment-1761522991):

```
TASK [run-workloads : run kube-kube burner workload node-density] ****************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["./run.sh"], "delta": "1:02:38.334207", "end": "2023-10-16 09:04:27.789849", "msg": "non-zero return code", "rc": 1, "start": "2023-10-16 08:01:49.455642", "stderr": "Error from server (NotFound): namespaces \"openshift-monitoring\" not found
error: the server doesn't have a resource type \"network\"
error: the server doesn't have a resource type \"IngressController\"
No resources found
error: the server doesn't have a resource type \"infrastructure\"
error: the server doesn't have a resource type \"network\"
error: the server doesn't have a resource type \"IngressController\"
No resources found
error: the server doesn't have a resource type \"infrastructure\"
time=\"2023-10-16 08:01:51\" level=info msg=\"🔥 Starting kube-burner (0.17.3@c38fe7eb37c62686b68e2b64bdc8311a4d73d8f1) with UUID 5dff6ffc-0c8f-4d69-905b-8827bba3f60f\"
time=\"2023-10-16 08:01:51\" level=info msg=\"📈 Creating measurement factory\"
time=\"2023-10-16 08:01:51\" level=info msg=\"Registered measurement: podLatency\"
time=\"2023-10-16 08:01:51\" level=info msg=\"Preparing create job: node-density\"
time=\"2023-10-16 08:01:51\" level=info msg=\"Job node-density: 235 iterations with 1 Pod replicas\"
time=\"2023-10-16 08:01:51\" level=info msg=\"Pre-load: images from job node-density\"
time=\"2023-10-16 08:01:51\" level=info msg=\"Pre-load: Creating DaemonSet using image gcr.io/google_containers/pause:3.1 in namespace preload-kube-burner\"
time=\"2023-10-16 08:01:51\" level=info msg=\"Pre-load: Sleeping for 2m0s\"
time=\"2023-10-16 08:03:51\" level=info msg=\"Pre-load: Deleting namespace preload-kube-burner\"
time=\"2023-10-16 08:03:51\" level=info msg=\"Deleting namespaces with label kube-burner-preload=true\"
time=\"2023-10-16 08:03:51\" level=info msg=\"Waiting for namespaces to be definitely deleted\"
time=\"2023-10-16 08:04:02\" level=info msg=\"Triggering job: node-density\"
time=\"2023-10-16 08:04:02\" level=info msg=\"Creating Pod latency watcher for node-density\"
time=\"2023-10-16 08:04:02\" level=info msg=\"QPS: 10\"
time=\"2023-10-16 08:04:02\" level=info msg=\"Burst: 10\"
time=\"2023-10-16 08:04:02\" level=info msg=\"Running job node-density\"
time=\"2023-10-16 08:04:25\" level=info msg=\"Waiting up to 1h0m0s for actions to be completed\"
time=\"2023-10-16 09:04:25\" level=info msg=\"Actions in namespace 5dff6ffc-0c8f-4d69-905b-8827bba3f60f completed\"
time=\"2023-10-16 09:04:25\" level=info msg=\"Finished the create job in 1h0m23s\"
time=\"2023-10-16 09:04:25\" level=info msg=\"Verifying created objects\"
time=\"2023-10-16 09:04:26\" level=info msg=\"pods found: 235 Expected: 235\"
time=\"2023-10-16 09:04:26\" level=info msg=\"Stopping measurement: podLatency\"
time=\"2023-10-16 09:04:26\" level=info msg=\"Evaluating latency thresholds\"
time=\"2023-10-16 09:04:26\" level=error msg=\"❗ P99 Ready latency (36.33s) higher than configured threshold: 5s\"
time=\"2023-10-16 09:04:26\" level=info msg=\"node-density: PodScheduled 50th: 0 99th: 203 max: 207 avg: 13\"
time=\"2023-10-16 09:04:26\" level=info msg=\"node-density: ContainersReady 50th: 26722 99th: 36333 max: 36966 avg: 24877\"
time=\"2023-10-16 09:04:26\" level=info msg=\"node-density: Initialized 50th: 0 99th: 1221 max: 1235 avg: 127\"
time=\"2023-10-16 09:04:26\" level=info msg=\"node-density: Ready 50th: 26722 99th: 36333 max: 36966 avg: 24877\"
time=\"2023-10-16 09:04:26\" level=info msg=\"Job node-density took 3623.17 seconds\"
time=\"2023-10-16 09:04:26\" level=info msg=\"Finished execution with UUID: 5dff6ffc-0c8f-4d69-905b-8827bba3f60f\"
time=\"2023-10-16 09:04:26\" level=info msg=\"👋 Exiting kube-burner\"
error: the server doesn't have a resource type \"infrastructure\"
error: the server doesn't have a resource type \"networks\"
```

**Comment by sjug** [comment]
> * Failed to start because host name is not valid
>   
>   * This is the same issue I found when running `run-perf.yml` weeks ago
>     
>     * [USHIFT-1685: Ansible Improvements Catch-up #2284 (comment)](https://github.com/openshift/microshift/pull/2284#issuecomment-1735065440)
>   * workaround:
>     
>     * on ansible/setup-node.yml set hosts variable in lines 10 and 31 to microshift-dev `hosts: microshift-dev`
This is an issue with your setup. 

Line 10 of setup-node.yml is:
```
- name: create vm and set up localhost
  hosts: localhost
```
This is a task that acts on the localhost and not on `microshift-dev`.

Line 31 of setup node is:
```
- name: entitle host and manage repos
  hosts: microshift
```

This takes the hosts in the group called `microshift` in the inventory file, which matches:

```
[microshift]
microshift-dev ansible_host="{{ ansible_host_var | default('microshift-dev') }}"
```

Hardcoding it to `microshift-dev` is not the answer. You need to fix your host resolution on that system.


> * The role 'quick-microshift-boot' was not found
>   
>   * The error appears to be in '/home/microshift/microshift/ansible/setup-node.yml': line 81, column 7, but may be elsewhere in the file depending on the exact syntax problem.
>   * workaround:
>     
>     * remove this task because I couldn’t find in the repo any reference to quick-microshift-boot role

Correct, I have not yet pushed a quick-microshift-boot, which I carry locally. I have removed the reference.


> * TASK [fetch-kubeconfig : create .kube folder in home directory if missing]
>   
>   * "The conditional check 'not kubeconfig_directory_check.stat.isdir' failed. The error was: error while evaluating conditional (not kubeconfig_directory_check.stat.isdir): 'dict object' has no attribute 'isdir'.
>   * workaround
>     
>     * add additional condition to check  if folder exists before checking if is a directory on ansible/roles/fetch-kubeconfig/tasks/main.yml:19
>       ```
>       - name: create .kube folder in home directory if missing
>         ansible.builtin.file:
>           path: "{{ kubeconfig_directory }}"
>           state: directory
>         delegate_to: localhost
>         when:
>         - kubeconfig_directory_check.stat.exists
>         - not kubeconfig_directory_check.stat.isdir
>       ```

I've pushed a fix for this as well.

> * TASK [setup-localhost : ansible.builtin.command]
>   
>   * fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_user' is undefined. 'ansible_user' is undefined\n\nThe error appears to be in '/home/microshift/jenkins-microshift-microshift-create-buildvm-3926/ansible/roles/setup-localhost/tasks/main.yml'
>   * workaround
>     
>     * add manually the remote hostname in ansible/roles/fetch-kubeconfig/defaults/main.yml:6
>       `kubeconfig_remote_file: "/var/lib/microshift/resources/kubeadmin/dhcp-1-235-90.arm.eng.rdu2.redhat.com/kubeconfig"`

This role has nothing to do with this PR, nothing was changed here.

> * TASK [run-workloads : extract kube-burner files]
>   
>   * An exception occurred during task execution. fatal: [localhost]: FAILED! => {"changed": false, "msg": "dest '/home/microshift/.local/bin' must be an existing dir"}
>   * few tasks before that directory was found because it’s in the PATH
>   * workaround:
>     
>     * created manually in the ansible host the directory /home/microshift/.local/bin that only existed in the PATH
>       `mkdir -p /home/microshift/.local/bin`

Pushed fix for this.

**Comment by sjug** [comment]
> I got this error when running it (applying workarounds from my previous comment [#2455 (comment)](https://github.com/openshift/microshift/pull/2455#issuecomment-1761522991)):
> 
> ```
> TASK [run-workloads : run kube-kube burner workload node-density] ****************************************************
> fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["./run.sh"], "delta": "1:02:38.334207", "end": "2023-10-16 09:04:27.789849", "msg": "non-zero return code", "rc": 1, "start": "2023-10-16 08:01:49.455642", "stderr": "Error from server (NotFound): namespaces \"openshift-monitoring\" not found

How have you run this? In the log it says nothing about `openshift-monitoring`?


> Where/How can I change the threshold Ready latency? Why does it take 1h for actions to be completed? How can I reduce it?

The actions were not completed and it timed out in an hour.

**Comment by agullon** [comment]
Hi @sjug thank you for the fixes, I rerun it on a VM with 4 CPUs and got new failures:

-   time=\"2023-10-18 08:39:32\" level=error msg=\"❗ P99 Ready latency (10.75s) higher than configured threshold: 5s\"
	-   workaround
		- manually edit pod latency on [/tmp/e2e-benchmarking/workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml:15](https://github.com/cloud-bulldozer/kube-burner/blob/master/cmd/kube-burner/ocp-config/node-density/node-density.yml#L15) to `30s`
    

-   TASK [run-workloads : cleanup previous workload namespace] ***********************************************
	- An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'kubernetes'
	- fatal: [localhost]: FAILED! => {"changed": false, "error": "No module named 'kubernetes'", "msg": "Failed to import the required Python library (kubernetes) on microshift-dev.local's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
    

-   openshift-monitoring namespace is missing in Microshift, so I’m not able to check Prometheus metrics

**Comment by agullon** [comment]
> > * time="2023-10-18 08:39:32" level=error msg="❗ P99 Ready latency (10.75s) higher than configured threshold: 5s"
> >   
> >   * workaround
> >     
> >     * manually edit pod latency on [/tmp/e2e-benchmarking/workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml:15](https://github.com/cloud-bulldozer/kube-burner/blob/master/cmd/kube-burner/ocp-config/node-density/node-density.yml#L15) to `30s`
> 
> I just pushed a new parameter for this `kube_burner_pod_ready`, I've set it to 10s right now but maybe a higher default would be better? Otherwise you can just override as normal.
> 
thanks, just tested your change, it's working

> > * TASK [run-workloads : cleanup previous workload namespace] ***********************************************
> >   
> >   * An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'kubernetes'
> >   * fatal: [localhost]: FAILED! => {"changed": false, "error": "No module named 'kubernetes'", "msg": "Failed to import the required Python library (kubernetes) on microshift-dev.local's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
> 
> The local host/ansible node will need the python "kubernetes" module. I can add that to a localhost setup role.
> 
working on this, I'll add an ansible task to pip install that module
> > * openshift-monitoring namespace is missing in Microshift, so I’m not able to check Prometheus metrics
> 
> Correct, we have roles that install and setup prometheus and grafana. I'm working on the e2e-benchmarking scripts to enable an out of cluster prometheus metrics source. However at the moment they're very much set up for the normal OCP happy path.
thanks!

**Comment by agullon** [comment]
hi @sjug created this PR https://github.com/sjug/microshift/pull/2 to install missing kubernetes python module

**Comment by agullon** [comment]
hi @sjug created this PR https://github.com/sjug/microshift/pull/3 to set be able to set a valid path to the kubeconfig file in the microshift host

**Comment by agullon** [comment]
hi @sjug I need your help to add these 2 task into a role:
```
- name: Install pip
  yum:
    name: python3-pip
    state: present

- name: Install 'kubernetes' Python library
  pip:
    name: kubernetes
    state: present
```
I think they should go into `setup-localhost` but they need to be run as root, so, is it safe to run the role as root?

**Comment by sjug** [comment]
> hi @sjug I need your help to add these 2 task into a role:
> 
> ```
> - name: Install pip
>   yum:
>     name: python3-pip
>     state: present
> 
> - name: Install 'kubernetes' Python library
>   pip:
>     name: kubernetes
>     state: present
> ```
> 
> I think they should go into `setup-localhost` but they need to be run as root, so, is it safe to run the role as root?

So ansible is able to escalate privs to run roles or tasks. There's a `python3-kubernetes` package available so we'd just want to install that rather than using `pip`. Give my changes a try.

**Comment by agullon** [comment]
hi @sjug `python3-kubernetes` installation package needs to be run as root:
```
TASK [setup-localhost : install local ansible prereq pacakges] *****************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "This command has to be run under the root user.", "results": []}
```

**Comment by agullon** [comment]
hi @sjug can we use the var `ansible_fqdn` instead `ansible_hostname` in the [`fetch-kubeconfig` role vars](https://github.com/sjug/microshift/blob/add_performance_workloads/ansible/roles/fetch-kubeconfig/defaults/main.yml#L6)?

`ansible_hostname` returns only `microshift-dev` but `ansible_fqdn` return `microshift-dev.local`  and from the VM I got
```
> ls /var/lib/microshift/resources/kubeadmin/
dhcp-1-235-101.arm.eng.rdu2.redhat.com	kubeconfig  microshift-dev.local
```

**Comment by sjug** [comment]
> hi @sjug `python3-kubernetes` installation package needs to be run as root:
> 
> ```
> TASK [setup-localhost : install local ansible prereq pacakges] *****************
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "This command has to be run under the root user.", "results": []}
> ```
> 
> A possible solution is to define `become: yes` or `become: no` in every `setup-localhost` task instead of setting `become: no` as var before running the whole role in https://github.com/sjug/microshift/blob/add_performance_workloads/ansible/setup-node.yml#L12

Yes, I am aware. That's why I set `become: yes` on the `install local ansible prereq packages` task, but it seems it did not work?



> hi @sjug can we use the var `ansible_fqdn` instead `ansible_hostname` in the [`fetch-kubeconfig` role vars](https://github.com/sjug/microshift/blob/add_performance_workloads/ansible/roles/fetch-kubeconfig/defaults/main.yml#L6)?
> 
> `ansible_hostname` returns only `microshift-dev` but `ansible_fqdn` return `microshift-dev.local` and from the VM I got
> 
> ```
> > ls /var/lib/microshift/resources/kubeadmin/
> dhcp-1-235-101.arm.eng.rdu2.redhat.com	kubeconfig  microshift-dev.local
> ```

What is the hostname of that box you're on?

**Comment by sjug** [comment]
Both should be resolved now.

**Comment by agullon** [comment]
> Both should be resolved now.

Thanks @sjug . Sucessfully tested, although Prometheus endpoint or Grafana dashboards are not available.

**Comment by ggiguash** [comment]
Tested and verified by @agullon, approving
/lgtm

**Pull request merged**
