### PR TITLE
USHIFT-1517: add junit output for image build and VM boot steps

### PR DESCRIPTION
**Pull request by dhellmann**

### CODE REVIEW

**Comment by dhellmann** [comment]
/assign @pacevedom 

I think this is ready for review.

**Review by pacevedom — APPROVED** [review]
/lgtm
Maybe for further work it would be nice to have elapsed time per junit entry.

**Comment by dhellmann** [comment]
@pacevedom I had to rebase

**Comment by ggiguash** [comment]
The `microshift-metal-tests` relevant for this change passed. Overriding the remaining job to save CI cycles.
/override e2e-openshift-conformance-reduced

**Pull request merged**
