### PR TITLE
USHIFT-2963: Start using RHEL-9.4 ISO for booting RHEL-based tests

### PR DESCRIPTION
**Pull request by ggiguash**
Also fixes [USHIFT-2926](https://issues.redhat.com//browse/USHIFT-2926)

### CODE REVIEW

**Comment by ggiguash** [comment]
The failure is not related to the error. Saving CI cycles.
/override ci/prow/metal-periodic-test-arm

**Review by pacevedom — COMMENTED** [review]
/lgtm

**Comment by ggiguash** [comment]
Changes not related to osbuilder tests.
/override ci/prow/metal-periodic-test

**Pull request merged**
