### PR TITLE
USHIFT-2926: Implement bootc-image-builder support for creating CentOS ISO files

### PR DESCRIPTION
**Pull request by ggiguash**
Also addresses [USHIFT-2983](https://issues.redhat.com//browse/USHIFT-2983)

### CODE REVIEW

**Comment by ggiguash** [comment]
Test failures are due to the problem fixed by https://github.com/openshift/microshift/pull/3286

**Comment by copejon** [comment]
This looks good. Will LGTM as we expect the arm tests to pass now

/lgtm

**Pull request merged**
