### PR TITLE
USHIFT-2362: Update origin

### PR DESCRIPTION
**Pull request by pacevedom**
Update origin fork to latest version and:
- Use submodules. Eases updates.
- Use patches. Eases cherry-picking changes when updating code base. Eases carry patching to upstream.
- Adapt run.sh to handle everything automatically.

**Which issue(s) this PR addresses**:

Closes #<Issue Number>

### CODE REVIEW

**Comment by pacevedom** [comment]
/hold
Fixing an issue with synthetic monitor tests

**Comment by pmtk** [comment]
I like this. Much better overview of the diff compared to openshift/origin.

**Pull request merged**
