### PR TITLE
provide more complete route schema.

### PR DESCRIPTION
**Pull request by deads2k**
like https://github.com/openshift/microshift/pull/788 with an auto-generated schema

### CODE REVIEW

**Comment by oglok** [comment]
Why not changing the existing #788 PR?

@Miciah generated this CRD with validations and default values I think we should use:

https://github.com/openshift/api/pull/1228/files#diff-6f2a93a87b2c5d86ab777d70320bba54ba8395569f69dc4b4446ac9c3cb76480

**Comment by deads2k** [comment]
> Why not changing the existing #788 PR?
> 
> @Miciah generated this CRD with validations and default values I think we should use:

Just making the delta clearer.  I've pushed into both now.

**Comment by deads2k** [comment]
https://github.com/openshift/microshift/pull/788 is happy

/close

**Pull request closed without merging**
