### PR TITLE
USHIFT-233: move the version config map to match where it will be in OCP

### PR DESCRIPTION
**Pull request by dhellmann**
Closes: [USHIFT-233](https://issues.redhat.com//browse/USHIFT-233)

This is related to https://github.com/openshift/enhancements/pull/1203, but we can go ahead and take it now to make less work to update test suite changes later.

### CODE REVIEW

**Review by pacevedom — APPROVED** [review]
/lgtm

**Comment by mangelajo** [comment]
@dhellmann it complains on the bindata filemodes, may be it needs a rebase? https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_microshift/814/pull-ci-openshift-microshift-main-verify/1555955628197810176#1:build-log.txt%3A38

**Comment by dhellmann** [comment]
/hold cancel

The verify job failure was correct, the bindata.go module wasn't updated properly.

**Comment by dhellmann** [comment]
In the absence of any consensus about how this should work for OpenShift more generally, we don't need this PR.

**Pull request closed without merging**
