### PR TITLE
NO-ISSUE: Move kustomize.robot to standard-suite2

### PR DESCRIPTION
**Pull request by pmtk**
Due to recent addition of more kustomization tests and wait for greenboot standard-suite1 started intermittently exceeding 30 minutes timeout.

### CODE REVIEW

**Review by pacevedom — APPROVED** [review]
/lgtm

**Comment by ggiguash** [comment]
/hold
Can we move tests around instead, or split the "standard" suite to the 3rd one?
I would really like to uphold the artificial limit of 30m per suite in pre-submits.

**Comment by pacevedom** [comment]
/lgtm
standard suite 2 has about ~10min until the 30min mark we are holding on to.

**Pull request merged**
