### PR TITLE
NO-ISSUE: Robot framework formatter

### PR DESCRIPTION
**Pull request by pmtk**

### CODE REVIEW

**Comment by dhellmann** [comment]
I love it. Let's give some other members of the team a chance to take a look, too. 

/assign @pacevedom @jogeo @copejon @eggfoobar

**Comment by eggfoobar** [comment]
Very nice! Do we want to add a quick make file task for it as well?

**Comment by pmtk** [comment]
> Very nice! Do we want to add a quick make file task for it as well?

Added.
Though, I feel like we should organize RF related files (there's some duplication rn in regards to setting up the venv)

**Pull request merged**
