### PR TITLE
USHIFT-962: Standardize network configuration in config.yaml

### PR DESCRIPTION
**Pull request by ggiguash**
Closes [USHIFT-962](https://issues.redhat.com//browse/USHIFT-962)

### CODE REVIEW

**Comment by dhellmann** [comment]
This looks good. I wonder if it needs to be rebased to pick up the container-selinux fix for CI?

**Comment by ggiguash** [comment]
Looks like tests were stuck. I rebased to the latest main branch and retriggerred the tests.

**Comment by dhellmann** [comment]
This will definitely be worth a release note.

/lgtm

**Pull request merged**
