### PR TITLE
USHIFT-1426: remove openvswitch pin in test image blueprint

### PR DESCRIPTION
**Pull request by dhellmann**
This depends on #2114

/assign @ggiguash @zshi-redhat

### CODE REVIEW

**Comment by dhellmann** [comment]
/hold

This PR passes because the 4.13 RPM still pins openvswitch3.1 to the version where the RPM installation creates the user and group properly. We need to merge #2114 and then have a new 4.13 z-stream release without the pin, then re-test this change.

**Comment by dhellmann** [comment]
`microshift-4.13.8-202308031445.p0.g717bea4.assembly.4.13.8.el9` includes 236f3377699fd269623a6258b5f37e2f4751ac09, which removes the version cap for openvswitch3.1 from the release-4.13 branch but that version does not appear to be available through public repos, yet.

**Comment by ggiguash** [comment]
Looks like 4.13.8 has been tagged. Unholding the PR.
```
$ sudo dnf clean all
$ sudo dnf search --showduplicates  microshift*  | grep 4.13.8
Last metadata expiration check: 0:00:25 ago on Tue 08 Aug 2023 01:20:54 PM UTC.
microshift-4.13.8-202308031445.p0.g717bea4.assembly.4.13.8.el9.x86_64 : MicroShift service
microshift-greenboot-4.13.8-202308031445.p0.g717bea4.assembly.4.13.8.el9.noarch : Greenboot components for MicroShift
microshift-networking-4.13.8-202308031445.p0.g717bea4.assembly.4.13.8.el9.x86_64 : Networking components for MicroShift
microshift-release-info-4.13.8-202308031445.p0.g717bea4.assembly.4.13.8.el9.noarch : Release information for MicroShift
microshift-selinux-4.13.8-202308031445.p0.g717bea4.assembly.4.13.8.el9.noarch : SELinux policies for MicroShift
```

/unhold

**Pull request merged**
