### PR TITLE
Rebase to 4.12 nightly

### PR DESCRIPTION
**Pull request by fzdarsky**
Closes [USHIFT-418](https://issues.redhat.com//browse/USHIFT-418)
Closes [USHIFT-419](https://issues.redhat.com//browse/USHIFT-419)
Closes [USHIFT-420](https://issues.redhat.com//browse/USHIFT-420)

### CODE REVIEW

**Comment by fzdarsky** [comment]
Most things seem to work, except for that the ovnkube-master container keeps crashlooping due to a nil pointer dereference.

**Review by oglok — COMMENTED** [review]
/lgtm

**Pull request merged**
