### PR TITLE
OCPBUGS-14678: microshift-etcd shuts down independently

### PR DESCRIPTION
**Pull request by eslutsky**
microshift is running microshift-etcd binary as systemd [transient](https://github.com/openshift/microshift/blob/14adeba0d460b38c898d9b730806eb4f011b49cd/pkg/controllers/etcd.go#L73) unit ,

current behavior after microshift.service is stopped:

1. systemd sends its term signal  to the microshift.service,
2. microshift ServiceManager  stopping  the microshift-etcd.transient unit https://github.com/openshift/microshift/blob/14adeba0d460b38c898d9b730806eb4f011b49cd/pkg/controllers/etcd.go#L119-L126
3. microshift  exits prematurely: https://github.com/openshift/microshift/blob/14adeba0d460b38c898d9b730806eb4f011b49cd/pkg/controllers/etcd.go#L107-L116

this behaviour causes  unclean microshift services shutdown (see also [USHIFT-1533](https://issues.redhat.com//browse/USHIFT-1533)),

which is  evident in the journal log:
```microshift-etcd process terminated prematurely, restarting MicroShift```
it is also  explains why the shutdown happens so quickly .

the proposed change enforces the dependency order from systemd perspective, 
delegate the etcd shutdown to systemd  instead of ServiceManager.

side effect of this  change: the shutdown becomes  much slower.  

before the change:
```
> time systemctl stop microshift

real    0m0.087s
user    0m0.013s
sys     0m0.021s

> journalctl -u microshift.service | grep systemd
Sep 02 22:17:18 microshift-lenovo systemd[1]: Stopping MicroShift...
Sep 02 22:17:18 microshift-lenovo systemd[1]: microshift.service: Deactivated successfully.
Sep 02 22:17:18 microshift-lenovo systemd[1]: Stopped MicroShift.
Sep 02 22:17:18 microshift-lenovo systemd[1]: microshift.service: Consumed 28.903s CPU time.

>journalctl -u microshift-etcd.scope | grep systemd
Sep 02 22:17:18 microshift-lenovo systemd[1]: microshift-etcd.scope: Deactivated successfully.
Sep 02 22:17:18 microshift-lenovo systemd[1]: Stopped /usr/bin/microshift-etcd run.
Sep 02 22:17:18 microshift-lenovo systemd[1]: microshift-etcd.scope: Consumed 5.071s CPU time.


```

after the change:
```
> time systemctl stop microshift
real    1m0.098s
user    0m0.017s
sys     0m0.018s

> journalctl -u microshift.service | grep systemd
Sep 02 22:06:53 microshift-lenovo systemd[1]: Stopping MicroShift...
Sep 02 22:07:53 microshift-lenovo systemd[1]: microshift.service: Deactivated successfully.
Sep 02 22:07:53 microshift-lenovo systemd[1]: Stopped MicroShift.
Sep 02 22:07:53 microshift-lenovo systemd[1]: microshift.service: Consumed 24.946s CPU time.

> journalctl -u microshift-etcd.scope | grep systemd
Sep 02 22:07:53 microshift-lenovo systemd[1]: Stopping /usr/bin/microshift-etcd run...
Sep 02 22:07:53 microshift-lenovo systemd[1]: microshift-etcd.scope: Deactivated successfully.
Sep 02 22:07:53 microshift-lenovo systemd[1]: Stopped /usr/bin/microshift-etcd run.
Sep 02 22:07:53 microshift-lenovo systemd[1]: microshift-etcd.scope: Consumed 4.268s CPU time.
```

### CODE REVIEW

**Comment by dhellmann** [comment]
I'm glad this was such a small change, nice work, @eslutsky. Remove the WIP when it's ready for a full review.

/assign @pacevedom @dusk125

**Comment by dhellmann** [comment]
/assign @pmtk

Patryk, you were involved in the early implementation here with Allen, right?

**Comment by ggiguash** [comment]
I'm approving the PR and leaving it to @pmtk to review and merge
/approve

**Comment by pmtk** [comment]
This looks good to me.
If we want to address kube-apiserver and kube-controller-manager not completing, then it should be in another PR/ticket.

Since timeout was reduced from 60 to 15s, I'll let others take a look

**Pull request merged**
