### PR TITLE
USHIFT-4341: Implement bootc CNCF tests

### PR DESCRIPTION
**Pull request by ggiguash**

### CODE REVIEW

**Comment by ggiguash** [comment]
/hold 
The system configuration works and tests start normally. 
Waiting to confirm that the tests pass locally.

**Review by pacevedom — APPROVED** [review]
/lgtm

**Comment by ggiguash** [comment]
I confirm that CNCF tests are passing in the local setup.
/unhold

```
$ tail -6 e2e.log 
Ran 404 of 6603 Specs in 6172.640 seconds
SUCCESS! -- 404 Passed | 0 Failed | 0 Pending | 6199 Skipped
PASS

Ginkgo ran 1 suite in 1h42m53.093673003s
Test Suite Passed

$ jq < cncf_status.json
{
  "plugins": [
    {
      "plugin": "systemd-logs",
      "node": "el94-src-cncf-conformance-host1",
      "status": "complete",
      "result-status": "passed",
      "result-counts": {
        "passed": 1
      }
    },
    {
      "plugin": "systemd-logs",
      "node": "el94-src-cncf-conformance-host2",
      "status": "complete",
      "result-status": "passed",
      "result-counts": {
        "passed": 1
      }
    },
    {
      "plugin": "e2e",
      "node": "global",
      "status": "complete",
      "result-status": "passed",
      "result-counts": {
        "passed": 408,
        "skipped": 6199
      },
      "progress": {
        "name": "e2e",
        "node": "global",
        "timestamp": "2024-10-25T09:13:15.570327524Z",
        "msg": "Test Suite completed",
        "total": 404,
        "completed": 0
      }
    }
  ],
  "status": "complete",
  "tar-info": {
    "name": "202410250729_sonobuoy_a9b4aafa-5a52-407d-883f-ff64a6a5c80e.tar.gz",
    "created": "2024-10-25T09:13:43.880501654Z",
    "sha256": "0cdf1c841e84e20dabc0f955286579ede45198b5b2cc9cdd9739d0787bceb0af",
    "size": 2149970
  }
}
```

**Pull request merged**
