### PR TITLE
[release-4.17] USHIFT-4326: Remove the unnecessary openssl image dependency

### PR DESCRIPTION
**Pull request by ggiguash**

### CODE REVIEW

**Comment by ggiguash** [comment]
/override ci/prow/microshift-metal-tests ci/prow/microshift-metal-tests-arm

**Comment by eslutsky** [comment]
/override ci/prow/microshift-metal-tests ci/prow/microshift-metal-tests-arm
/override ci/prow/microshift-metal-tests ci/prow/microshift-metal-tests-arm-arm

**Comment by ggiguash** [comment]
/override ci/prow/microshift-metal-tests ci/prow/microshift-metal-tests-arm

**Pull request merged**
